CREATE NONCLUSTERED INDEX [IX_tbl_Summary_RskAdj_Activity__GroupingId] ON [rev].[tbl_Summary_RskAdj_Activity]
(
[GroupingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF
, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100 ) 


