CREATE TABLE [rev].[IntermediateEDSPartD]
(
	[IntermediateEDSPartDId] [BIGINT] IDENTITY(1, 1) NOT NULL ,
        [PaymentYear] [INT] NULL ,
        [ModelYear] [INT] NULL ,
        [PlanIdentifier] [INT] NULL ,
        [HICN] [VARCHAR](12) NULL ,
        [PartDRAFT] [CHAR](3) NULL ,
        [RxHCCLabel] [VARCHAR](50) NULL ,
        [RxHCCNumber] [INT] NULL ,
        [MinProcessBy] [DATETIME] NULL ,
        [MinThruDate] [DATETIME] NULL ,
        [MinProcessBySeqNum] [INT] NULL ,
        [MinThruDateSeqNum] [INT] NULL ,
        [Deleted] [CHAR](1) NULL ,
        [MinProcessbyDiagID] [INT] NULL ,
        [MinThruDateDiagID] [INT] NULL ,
        [MinProcessbyDiagCD] [VARCHAR](7) NULL ,
        [MinThruDateDiagCD] [VARCHAR](7) NULL ,
        [MinProcessByPCN] [VARCHAR](40) NULL ,
        [MinThruDatePCN] [VARCHAR](40) NULL ,
        [ProcessedPriorityThruDate] [DATETIME] NULL ,
        [ThruPriorityProcessedBy] [DATETIME] NULL ,
        [ProcessedPriorityFileID] [VARCHAR](18) NULL ,
        [ProcessedPriorityRAPSSourceID] [INT] NULL ,
        [ProcessedPriorityProviderID] [VARCHAR](40) NULL ,
        [ProcessedPriorityRAC] [CHAR](1) NULL ,
        [ThruPriorityFileID] [VARCHAR](18) NULL ,
        [ThruPriorityRAPSSourceID] [INT] NULL ,
        [ThruPriorityProviderID] [VARCHAR](40) NULL ,
        [ThruPriorityRAC] [CHAR](1) NULL ,
        [IMFFlag] [SMALLINT] NULL ,
        [RxHCCLabelOrig] [VARCHAR](50) NULL ,
        [LoadDateTime] [DATETIME] NOT NULL
)
