CREATE TABLE rev.PartCNewHCCOutputSParameter
(
	PartCNewHCCOutputSParameterID BIGINT IDENTITY(1,1) NOT NULL,
	PaymentYear INT NULL,
	ModelYear INT NULL,
	ProcessedByStartDate DATETIME NULL,
	ProcessedByEndDate DATETIME NULL,
	ProcessedByFlag CHAR(1) NULL,
	EncounterSource VARCHAR(20) NULL,
	PlanID VARCHAR(5) NULL,
	HICN VARCHAR(15) NULL,
	RAFactorType CHAR(2) NULL,
	HCC VARCHAR(20) NULL,
	HCCDescription VARCHAR(255) NULL,
	HCCFactor DECIMAL(20,4) NULL,
	HierarchyHCC VARCHAR(20) NULL,
	HierarchyHCCFactor DECIMAL(20,4) NULL,
	PreAdjustedFactor DECIMAL(20,4) NULL,
	AdjustedFinalFactor DECIMAL(20,4) NULL,
	MonthsInDCP INT NULL,
	MemberMonths INT NULL,
	BidAmount MONEY NULL,
	EstimatedValue MONEY NULL,
	RollForwardMonths INT NULL,
	AnnualizedEstimatedValue MONEY NULL,
	PBP VARCHAR(3) NULL,
	SCC VARCHAR(5) NULL,
	SweepDate DATETIME NULL,
	PopulatedDate DATETIME NULL,
	AgedStatus VARCHAR(20) NULL,
	UserID VARCHAR(128) NOT NULL,
	LoadDate DATETIME NOT NULL
)