CREATE TABLE [rev].[tbl_Summary_RskAdj_MMR]
    (
        [tbl_Summary_RskAdj_MMR_Id] [BIGINT] IDENTITY(1, 1) NOT NULL ,
        [PlanID] [INT] NULL ,
        [HICN] [VARCHAR](12) NULL ,
        [PaymentYear] [INT] NULL ,
        [PaymStart] [DATETIME] NULL ,
        [Gender] [CHAR](1) NULL ,
        [RskAdjAgeGrp] [CHAR](4) NULL ,
        [PartCRAFTProjected] [CHAR](2) NULL ,
        [PartCRAFTMMR] [CHAR](2) NULL ,
        [PartCDefaultIndicator] [CHAR](1) NULL ,
        [ORECRestated] [VARCHAR](5) NULL ,
        [ORECMMR] [VARCHAR](5) NULL ,
        [MedicaidRestated] [CHAR](1) NULL ,
        [MedicaidAddOnMMR] [CHAR](1) NULL ,
        [MedicaidMMR] [CHAR](1) NULL ,
        [PartCRiskScoreMMR] [DECIMAL](19, 4) NULL ,
        [SCC] [VARCHAR](10) NULL ,
        [OOA] [CHAR](1) NULL ,
        [PBP] [VARCHAR](6) NULL ,
        [MABID] [MONEY] NULL ,
        [PartAMonthlyPaymentRate] [MONEY] NULL ,
        [PartBMonthlyPaymentRate] [MONEY] NULL ,
        [HOSP] [CHAR](1) NULL ,
        [MSPFactor] [DECIMAL](9, 4) NULL ,
        [MonthsInLaggedDCP] [INT] NULL ,
        [MonthsInDCP] [INT] NULL ,
        [TotalPayment] [MONEY] NULL ,
        [TotalMAPaymentAmount] [MONEY] NULL ,
        [RiskPymtA] [MONEY] NULL ,
        [RiskPymtB] [MONEY] NULL ,
        [ESRD] [CHAR](1) NULL ,
        [PartDRAFTMMR] [CHAR](2) NULL ,
        [PartDLowIncomeIndicator] [INT] NULL ,
        [PriorPaymentYear] [INT] NULL ,
        [LoadDateTime] [DATETIME] NOT NULL ,
        [MedicaidDualStatusCode] [VARCHAR](2) NULL ,
        [Aged] [INT] NULL ,
        [BeneficiaryCurrentMedicaidStatus] [CHAR](1) NULL ,
        [AgeGrp] [VARCHAR](4) NULL ,
        [LowIncomePremiumSubsidy] [SMALLMONEY] NULL ,
        [RskadjFctrA] [DECIMAL](19, 4) NULL ,
        [PartDLowIncomeMultiplier] [DECIMAL](19, 2) NULL ,
        [PartDBasicPremiumAmount] [SMALLMONEY] NULL ,
        [PartDDirectSubsidyPaymentAmount] [SMALLMONEY] NULL ,
        [PartDRAFTProjected] [CHAR](2) NULL,
		[PartDRAFactor] [DECIMAL](19, 4) NULL,
		[PartDAged][INT] NULL,
		[TotalPartDPayment] [smallmoney] NULL,
		[PartD_BID] [smallmoney] NULL
    )
