CREATE TABLE [rev].[tbl_Summary_RskAdj_RAPS_MOR_Combined]
(
	[tbl_Summary_RskAdj_RAPS_MOR_CombinedId] [bigint] IDENTITY(1,1) NOT NULL,
	[PlanID] [int] NULL,
	[HICN] [varchar](12) NULL,
	[PaymentYear] [int] NULL,
	[PaymStart] [datetime] NULL,
	[ModelYear] [int] NULL,
	[Factor_category] [varchar](20) NULL,
	[Factor_Desc] [varchar](50) NULL,
	[Factor] [decimal](20, 4) NULL,
	[RAFT] [char](3) NULL,
	[HCC_Number] [int] NULL,
	[Min_ProcessBy] [datetime] NULL,
	[Min_ThruDate] [datetime] NULL,
	[Min_ProcessBy_SeqNum] [int] NULL,
	[Min_ThruDate_SeqNum] [int] NULL,
	[Min_Processby_DiagCD] [varchar](7) NULL,
	[Min_ThruDate_DiagCD] [varchar](7) NULL,
	[Min_ProcessBy_PCN] [varchar](40) NULL,
	[Min_ThruDate_PCN] [varchar](40) NULL,
	[Processed_Priority_Thru_Date] [datetime] NULL,
	[Thru_Priority_Processed_By] [datetime] NULL,
	[RAFT_ORIG] [char](2) NULL,
	[Processed_Priority_FileID] [varchar](18) NULL,
	[Processed_Priority_RAPS_Source_ID] [int] NULL,
	[Processed_Priority_Provider_ID] [varchar](40) NULL,
	[Processed_Priority_RAC] [char](1) NULL,
	[Thru_Priority_FileID] [varchar](18) NULL,
	[Thru_Priority_RAPS_Source_ID] [int] NULL,
	[Thru_Priority_Provider_ID] [varchar](40) NULL,
	[Thru_Priority_RAC] [char](1) NULL,
	[IMFFlag] [smallint] NULL,
	[Factor_Desc_ORIG] [varchar](50) NULL,
	[Factor_Desc_EstRecev] [varchar](50) NULL,
	[LoadDateTime] [datetime] NOT NULL,
	[Aged] [int] NULL,
	[LastAssignedHICN] VARCHAR(12) NULL

)
