ALTER TABLE etl.EstRecvSummaryPartC
ADD CONSTRAINT [PK_EstRecvSummaryPartCID] PRIMARY KEY CLUSTERED ([EstRecvSummaryPartCID] ASC) 
WITH (FILLFACTOR = 100 , ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);