ALTER TABLE [etl].[EstRecvPartitionKey] ADD  CONSTRAINT [PK_etl_EstRecvPartitionKey] PRIMARY KEY CLUSTERED 
(
[EstRecvPartitionKeyID] ASC, [PaymentYear] ASC, [MYU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100 ) ON [PRIMARY]
GO
