ALTER TABLE etl.PartDNewHCCOutputDParameter
ADD CONSTRAINT [PKetlPartDNewHCCOutputDParameterID] PRIMARY KEY CLUSTERED ([PartDNewHCCOutputDParameterID] ASC)
WITH (FILLFACTOR = 100 , ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)