ALTER TABLE [etl].[RAPSIntermediateForPartD] ADD  CONSTRAINT [PK_RAPSIntermediateForPartDID] PRIMARY KEY CLUSTERED 
(
[RAPSIntermediateForPartDID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 
