ALTER TABLE [etl].[tbl_Intermediate_RskAdj_RAPS_Preliminary] ADD  CONSTRAINT [PK_tbl_Intermediate_RskAdj_RAPS_PreliminaryID] PRIMARY KEY CLUSTERED 
(
[RAPS_PreliminaryId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 
