ALTER TABLE [etl].EstRecvDemographicsPartD ADD  CONSTRAINT [PK_etl_EstRecvDemographicsPartDID] PRIMARY KEY CLUSTERED 
(
[ID] ASC, [PaymentYear] ASC, [MYUFlag] ASC, [PartitionKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100 ) 
