CREATE NONCLUSTERED INDEX [IDX_tbl_RAPSEDS_HCCDetails_PaymentYear_HICN] ON [etl].[tbl_RAPSEDS_HCCDetails]
	(
	[PaymentYear] ASC,
	[PlanID] ASC,
	[HICN] ASC,
    [RAFactorType] ASC
	)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO