CREATE NONCLUSTERED INDEX [idx_HICN_ServiceStartDate]
    ON [etl].[EligibilityRecyclingCheck]([HICN] ASC, [ServiceStartDate] ASC)
    INCLUDE([ContractNumber], [ServiceEndDate]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

