ALTER TABLE [ref].[ExtractStatus]
	ADD CONSTRAINT [PK_ExtractStatus] PRIMARY KEY CLUSTERED ([ExtractStatusID] ASC)
	WITH (FILLFACTOR = 100 , ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);