/**********************************************************************************
Get Source Gap data and populate it into temp prodsupport table
**********************************************************************************/

drop table if exists ProdSupport.dbo.tbl_GAP_Diags_Add 

select 
	left(DOSEnd, 4) as DOS_year,
	MemberNumber as MBI,
	FinalMemberNumber as HICN,
	DiagnosisCode,
	DOSStart,
	DOSEnd,
	ProviderType
into ProdSupport.dbo.tbl_GAP_Diags_Add 
from ReportingETL.[HRP\hasan.farooqui].AETGapCheck_000a_Source
where RunID = 1 and Status = 'A'

drop table if exists #tbl_GAP_Diags_Add_Members

select HICN
into #tbl_GAP_Diags_Add_Members
from
(
select distinct HICN from ProdSupport.dbo.tbl_GAP_Diags_Add
union
select distinct MBI from ProdSupport.dbo.tbl_GAP_Diags_Add
) a


drop table if exists #tbl_GAP_Diags_Add_AltHICN

select distinct MBI, HICN
into #tbl_GAP_Diags_Add_AltHICN
from ProdSupport.dbo.tbl_GAP_Diags_Add
where MBI <> HICN

select * from #tbl_GAP_Diags_Add_AltHICN

/**********************************************************************************
Diag HCC Mapping for 2020 PY
**********************************************************************************/

DROP TABLE IF EXISTS #Diag_HCC_Lookup

Select distinct 
	b.Payment_Year
	,b.Factor_Type
	,b.ICD10CD
	,b.HCC_Label
into 
	#Diag_HCC_Lookup
from
	HRPReporting.dbo.lk_Risk_Models_DiagHCC_ICD10 B  (nolock)  
where  
	B.Payment_Year in (2018) 
	and b.Factor_Type not in ('E','E1','E2','SE','ED')

select * from #Diag_HCC_Lookup


/**********************************************************************************
Combine with MMR
Get enrollment info and only perform analysis for eligible members
**********************************************************************************/

--Get Add Members from MMR

drop table if exists ProdSupport.dbo.Temp_SummaryMMR_Aetna
select 
	PaymentYear, 
	HICN, 
	PartCRAFTProjected RAFactorType,
	min(PartDRaftMMR) PartDRaftMMR, 
	max(PaymStart) PaymStart,
	max(PlanID) PlanID,
	count(distinct PaymStart) PaymentMonths 
into ProdSupport.dbo.Temp_SummaryMMR_Aetna
from 
	Aetna_report.rev.tbl_Summary_RskAdj_MMR (nolock)
where 
	HICN in (select HICN from ProdSupport.dbo.tbl_GAP_Diags_Add) 
	and PaymentYear in (2020) 
group by 
	PaymentYear, 
	HICN, 
	PartCRAFTProjected

select top 10 * from Aetna_report.rev.tbl_Summary_RskAdj_MMR

--select * from ProdSupport.dbo.Temp_SummaryMMR_Aetna

select
	isnull(alt.HICN, r.HICN) hicn, 
	FromDate, 
	ThruDate, 
	DiagnosisCode, 
	ProviderType
into #RAPS_DiagHCC_Rollup
from
	Aetna_Report.dbo.RAPS_DiagHCC_Rollup r
	left join #tbl_GAP_Diags_Add_AltHICN alt
	on r.HICN = alt.MBI
where
	r.hicn in (select hicn from #tbl_GAP_Diags_Add_Members)
	and YEAR(r.Thrudate) = 2019 
	and Accepted = 1 
	and Deleted is null


/**********************************************************************************
Combine with other HCC records and join with MMR
**********************************************************************************/

--Get all diagnoses from RAPS
drop table if exists ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna

truncate table ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna

insert into ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna
select distinct 
	EncounterSource = 'RAPS', 
	PaymentYear = YEAR(ThruDate) + 1, 
	a.HICN, 
	FromDate, 
	ThruDate, 
	DiagnosisCode, 
	ProviderType,
	HCC = lk.HCC_Label,
	'N' IsAdded,
	m.RAFactorTYpe RAFactorType,
	m.PlanID
into ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna
from #RAPS_DiagHCC_Rollup a
	inner join ProdSupport.dbo.Temp_SummaryMMR_Aetna m
	on a.hicn = m.hicn
	left join #Diag_HCC_Lookup lk
	on a.DiagnosisCode = lk.ICD10CD
    AND m.PaymentYear = lk.Payment_Year
	and m.RAFactorTYpe = lk.Factor_Type


-- ADD interaction logic here

--Add all diagnoses from Adds
insert into ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna
select distinct 
	'RAPS', 
	YEAR(DOSEnd) + 1, 	
	a.HICN, 
	DOSStart, 
	DOSEnd, 
	DiagnosisCode,
	ProviderType,
	HCC = lk.HCC_Label,
	'Y' as IsAdded,
	m.RAFactorTYpe RAFactorType,
	m.PlanID
from 
	ProdSupport.dbo.tbl_GAP_Diags_Add a 
	inner join ProdSupport.dbo.Temp_SummaryMMR_Aetna m
	on a.HICN = m.HICN
	left join #Diag_HCC_Lookup lk
	on a.DiagnosisCode = lk.ICD10CD
    AND m.PaymentYear = lk.Payment_Year
	and m.RAFactorTYpe = lk.Factor_Type
where a.DOS_year = 2019 

-- Add interaction logic here

--Get New HCCs generated by Add file
drop table if exists ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna

truncate table ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna

insert into ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna
select distinct 
	PaymentYear, 
	HICN, 
	HCC, 
	Hierarchy = CAST(NULL as varchar(1)), 
	HeirHCC = CAST(NULL as varchar(10)), 
	PlanID,
	RAFactorType
into ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna
from 
	ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna
where 
	HCC is not null 
	and IsAdded = 'Y'
Except
select distinct 
	PaymentYear, 
	HICN, 
	HCC, 
	NULL, 
	NULL,
	PlanID,
	RAFactorType
from 
	ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna
where 
	HCC is not null 
	and IsAdded = 'N'


--Apply Heirarchy

UPDATE A
SET Hierarchy = 'L'
FROM ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna A
WHERE 
	EXISTS
    (SELECT 1
		from ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna B
		JOIN HRPReporting.dbo.lk_Risk_Models_Hierarchy C
            ON A.HICN = B.HICN
               AND B.HCC = C.HCC_KEEP
               AND A.HCC = C.HCC_DROP
               AND A.PaymentYear = B.PaymentYear
               AND C.RA_FACTOR_TYPE = B.RAFactorType
        where IsAdded = 'N'
	)


UPDATE A
SET Hierarchy = 'L'
FROM ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna A
WHERE 
	EXISTS
    (SELECT 1
		from ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna B
		JOIN HRPReporting.dbo.lk_Risk_Models_Hierarchy C
            ON A.HICN = B.HICN
               AND B.HCC = C.HCC_KEEP
               AND A.HCC = C.HCC_DROP
               AND A.PaymentYear = B.PaymentYear
               AND C.RA_FACTOR_TYPE = B.RAFactorType
	)


UPDATE A
SET Hierarchy = 'H'
FROM ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna A
WHERE Hierarchy is null
AND	EXISTS
    (SELECT 1
		from ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna B
		JOIN HRPReporting.dbo.lk_Risk_Models_Hierarchy C
            ON A.HICN = B.HICN
               AND A.HCC = C.HCC_KEEP
               AND B.HCC = C.HCC_DROP
               AND A.PaymentYear = B.PaymentYear
               AND C.RA_FACTOR_TYPE = B.RAFactorType
        where IsAdded = 'N'
	)


drop table if exists #HierHCC

select distinct a.PaymentYear, a.HICN, a.HCC, b.HCC HierHCC, RANK() over (partition by a.hicn, a.hcc order by b.hcc) rnk
into #HierHCC
from 
      ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna a
      join ProdSupport.dbo.tbl_GAP_All_Diags_RAPS_PartC_Aetna b
      on a.PaymentYear = b.PaymentYear
      and a.HICN = b.HICN
      join HRPReporting.dbo.lk_Risk_Models_Hierarchy C
      on a.HCC = c.HCC_KEEP
      and b.HCC = c.HCC_DROP
      and b.PaymentYear = c.Payment_Year
      and b.RAFactorType = c.RA_FACTOR_TYPE 
where 
      a.Hierarchy = 'H'


update a
set 
	a.HeirHCC = b.HierHCC
from ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna a
join #HierHCC b
on a.HICN = b.HICN
and a.HCC = b.HCC
and a.PaymentYear = b.PaymentYear
and b.rnk = 1


/**********************************************************************************

**********************************************************************************/

drop table #temp
select
	a.PaymentYear, 
	a.HICN, 
	a.HCC, 
	a.HeirHCC, 
	a.PlanID, 
	a.RAFactorType
into #temp
from
	ProdSupport.dbo.tbl_GAP_HCC_RAPS_PartC_Aetna a
Where
	a.Hierarchy is NULL or a.Hierarchy = 'H'

--------------------------------------------
