CREATE TABLE Valuation.LogConfigSubProjectSubstringPattern
    (
     [LogConfigSubProjectSubstringPatternId] [INT] IDENTITY(1, 1)
                                                   NOT NULL
   , [Action] [CHAR](1) NULL
   , [SubProjectSubstringPatternId] [INT] NULL
   , [ClientId] [INT] NULL
   , [ClientId_old] [INT] NULL
   , [ProjectId] [INT] NULL
   , [ProjectId_old] [INT] NULL
   , [SubProjectId] [INT] NULL
   , [SubProjectId_old] [INT] NULL
   , [SubprojectDescription] [VARCHAR](255) NULL
   , [SubprojectDescription_old] [VARCHAR](255) NULL
   , [Source01] [NVARCHAR](255) NULL
   , [Source01_old] [NVARCHAR](255) NULL
   , [ProviderType] [CHAR](2) NULL
   , [ProviderType_old] [CHAR](2) NULL
   , [Type] [VARCHAR](15) NULL
   , [Type_old] [VARCHAR](15) NULL
   , [ProjectCategory] [VARCHAR](85) NULL
   , [ProjectCategory_old] [VARCHAR](85) NULL
   , [SubProjectSortOrder] [SMALLINT] NULL
   , [SubProjectSortOrder_old] [SMALLINT] NULL
   , [ActiveBDate] [DATE] NULL
   , [ActiveBDate_old] [DATE] NULL
   , [ActiveEDate] [DATE] NULL
   , [ActiveEDate_old] [DATE] NULL
   , [FilteredAuditActiveBDate] [DATE] NULL
   , [FilteredAuditActiveBDate_old] [DATE] NULL
   , [FilteredAuditActiveEDate] [DATE] NULL
   , [FilteredAuditActiveEDate_old] [DATE] NULL
   , [OnShoreOffShore] [CHAR](1) NULL
   , [OnShoreOffShore_old] [CHAR](1) NULL
   , [ID_VAN] [CHAR](1) NULL
   , [ID_VAN_old] [CHAR](1) NULL
   , [PMH] [CHAR](1) NULL
   , [PMH_old] [CHAR](1) NULL
   , [MissingSignature] [CHAR](1) NULL
   , [MissingSignature_old] [CHAR](1) NULL
   , [Filler01] [CHAR](1) NULL
   , [Filler01_old] [CHAR](1) NULL
   , [Filler02] [CHAR](1) NULL
   , [Filler02_old] [CHAR](1) NULL
   , [UniquePattern] [VARCHAR](255) NULL
   , [UniquePattern_old] [VARCHAR](255) NULL
   , [PCNStringPattern] [VARCHAR](255) NULL
   , [PCNStringPattern_old] [VARCHAR](255) NULL
   , [FailureReason] [VARCHAR](20) NULL
   , [FailureReason_old] [VARCHAR](20) NULL
   , [Added] [DATETIME] NULL
   , [Added_old] [DATETIME] NULL
   , [AddedBy] [VARCHAR](257) NULL
   , [AddedBy_old] [VARCHAR](257) NULL
   , [Reviewed] [DATETIME] NULL
   , [Reviewed_old] [DATETIME] NULL
   , [ReviewedBy] [VARCHAR](257) NULL
   , [ReviewedBy_old] [VARCHAR](257) NULL
   , [Edited] [DATETIME] NULL
   , [EditedBy] [VARCHAR](257) NULL
   , [Payment_Year] [CHAR](4) NULL
   , [Payment_Year_old] [CHAR](4) NULL
   , [SubprojectIdBPosition] [INT] NULL
   , [SubprojectIdBPosition_old] [INT] NULL
   , [SubprojectIdEPosition] [INT] NULL
   , [SubprojectIdEPosition_old] [INT] NULL
   , [SubprojectIdLength] [INT] NULL
   , [SubprojectIdLength_old] [INT] NULL
   , [ProviderIdBPosition] [INT] NULL
   , [ProviderIdBPosition_old] [INT] NULL
   , [ProviderIdLength] [INT] NULL
   , [ProviderIdLength_old] [INT] NULL
   , [ProviderIdEPosition] [INT] NULL
   , [ProviderIdEPosition_old] [INT] NULL
   , [UpdateStatement] [VARCHAR](4000) NULL

   , [UpdateStatement_old] [VARCHAR](4000) NULL
    )
