CREATE TABLE [Valuation].[LogRptSummaryTotalUnique](
	[LogRptSummaryTotalUniqueId] [int] IDENTITY(1,1) NOT NULL,
	[RptSummaryTotalUniqueId] [INT],
	[ClientId] [int]  NULL,
	[ClientId_old] [int]  NULL,
	[AutoProcessRunId] [int]  NULL,
	[AutoProcessRunId_old] [int]  NULL,
	[ReportHeader] [varchar](128) NULL,
	[ReportHeader_old] [varchar](128) NULL,
	[RowDisplay] [varchar](128)  NULL,
	[RowDisplay_old] [varchar](128)  NULL,
	[CodingThrough] [date]  NULL,
	[CodingThrough_old] [date]  NULL,
	[ValuationDelivered] [date]  NULL,
	[ValuationDelivered_old] [date] NULL,
	[ProjectCompletion] [numeric](34, 18) NULL,
	[ProjectCompletion_old] [numeric](34, 18) NULL,
	[ChartsCompleted] [int] NULL,
	[ChartsCompleted_old] [int] NULL,

	[HCCTotal_PartC] [int] NULL,
	[HCCTotal_PartC_old] [int] NULL,
	[EstRev_PartC] [money] NULL,
	[EstRev_PartC_old] [money] NULL,
	[HCCRealizationRate_PartC] [numeric](34, 18) NULL,
	[HCCRealizationRate_PartC_old] [numeric](34, 18) NULL,

	[EstRevPerChart_PartC] [numeric](34, 18) NULL,
	[EstRevPerChart_PartC_old] [numeric](34, 18) NULL,
	[EstRevPerHCC_PartC] [numeric](34, 18) NULL,
	[EstRevPerHCC_PartC_old] [numeric](34, 18) NULL,
	[HCCTotal_PartD] [int] NULL,
	[HCCTotal_PartD_old] [int] NULL,
	[EstRev_PartD] [money] NULL,
	[EstRev_PartD_old] [money] NULL,
	[HCCRealizationRate_PartD] [numeric](34, 18) NULL,
	[HCCRealizationRate_PartD_old] [numeric](34, 18) NULL,
	[EstRevPerChart_PartD] [numeric](34, 18) NULL,
	[EstRevPerChart_PartD_old] [numeric](34, 18) NULL,
	[EstRevPerHCC_PartD] [numeric](34, 18) NULL,
	[EstRevPerHCC_PartD_old] [numeric](34, 18) NULL,
	[TotalEstRev] [money] NULL,
	[TotalEstRev_old] [money] NULL,
	[TotalEstRevPerChart] [money] NULL,
	[TotalEstRevPerChart_old] [money] NULL,
	[Notes] [varchar](256) NULL,
	[Notes_old] [varchar](256) NULL,
	[SummaryYear] [bit] NULL,
	[SummaryYear_old] [bit] NULL,
	[ChartsRequested] [int] NULL,
	[ChartsRequested_old] [int] NULL,
	[IsSummary] [bit]  NULL,
	[IsSummary_old] [bit] NULL,
	[ReportBDate] [date] NULL,
	[ReportBDate_old] [date] NULL,
	[ReportEDate] [date] NULL,
	[ReportEDate_old] [date] NULL,
	[PopulatedDate] [datetime]  NULL,
	[PopulatedDate_old] [datetime] NULL,
	[Grouping] [varchar](10) NULL,
	[Grouping_old] [varchar](10) NULL,
	[GroupingOrder] [int] NULL,
	[GroupingOrder_old] [int] NULL,
	[Edited] [datetime] NULL,
	[EditedBy] [varchar](257) NULL,
	[Action] [CHAR](1) NULL

		
)
