CREATE TABLE [Valuation].[NewHCCPartC](
	[NewHCCPartCId] [bigint] IDENTITY(1,1) NOT NULL,
	[ProcessRunId] [int] NULL,
	[PlanId] [char](5) NULL,
	[Payment_Year] [int] NULL,
	[Model_Year] [int] NULL,
	[Processed_By_Start] [datetime] NULL,
	[Processed_By_End] [datetime] NULL,
	[HICN] [varchar](15) NULL,
	[Ra_Factor_Type] [char](2) NULL,
	[Processed_By_Flag] [char](1) NULL,
	[HCC] [varchar](50) NULL,
	[HCC_Description] [varchar](255) NULL,
	[HCC_FACTOR] [decimal](20, 4) NULL,
	[HIER_HCC] [varchar](24) NULL,
	[HIER_HCC_FACTOR] [decimal](20, 4) NULL,
	[Pre_Adjstd_Factor] [decimal](20, 4) NULL,
	[Adjstd_Final_Factor] [decimal](20, 4) NULL,
	[HCC_PROCESSED_PCN] [varchar](50) NULL,
	[HIER_HCC_PROCESSED_PCN] [varchar](50) NULL,
	[UNQ_CONDITIONS] [bit] NOT NULL,
	[Months_In_DCP] [int] NULL,
	[Member_Months] [int] NULL,
	[Bid_Amount] [money] NULL,
	[Estimated_Value] [money] NULL,
	[Rollforward_Months] [int] NULL,
	[Annualized_Estimated_Value] [money] NULL,
	[PBP] [char](3) NULL,
	[SCC] [char](5) NULL,
	[Processed_Priority_Processed_By] [datetime] NULL,
	[Processed_Priority_Thru_Date] [datetime] NULL,
	[Processed_Priority_Diag] [varchar](20) NULL,
	[Processed_Priority_FileID] [varchar](18) NULL,
	[Processed_Priority_RAC] [char](1) NULL,
	[Processed_Priority_RAPS_Source_ID] [varchar](50) NULL,
	[DOS_Priority_Processed_By] [datetime] NULL,
	[DOS_Priority_Thru_Date] [datetime] NULL,
	[DOS_Priority_PCN] [varchar](50) NULL,
	[DOS_Priority_Diag] [varchar](20) NULL,
	[DOS_Priority_FileId] [varchar](18) NULL,
	[DOS_Priority_RAC] [char](1) NULL,
	[DOS_PRIORITY_RAPS_SOURCE] [varchar](50) NULL,
	[Provider_Id] [varchar](40) NULL,
	[Provider_Last] [varchar](55) NULL,
	[Provider_First] [varchar](55) NULL,
	[Provider_Group] [varchar](80) NULL,
	[Provider_Address] [varchar](100) NULL,
	[Provider_City] [varchar](30) NULL,
	[Provider_State] [char](2) NULL,
	[Provider_Zip] [varchar](13) NULL,
	[Provider_Phone] [varchar](15) NULL,
	[Provider_Fax] [varchar](15) NULL,
	[Tax_Id] [varchar](55) NULL,
	[NPI] [varchar](20) NULL,
	[Sweep_Date] [date] NULL,
	[Populated_Date] [datetime] NULL,
	[PCN_SubprojectId] [varchar](32) NULL,
	[PCN_Coding_Entity] [varchar](32) NULL,
	[PCN_ProviderId] [varchar](32) NULL,
	[FailureReason] [varchar](20) NULL,
	[AgedStatus]  [varchar](20) NULL,
	[EncounterSource] [varchar](4) NULL,
	[ProcessedPriorityRecordID] [VARCHAR](80) NULL
);