ALTER TABLE [dbo].[Rollup_Log] ADD  CONSTRAINT [PK_Rollup_Log] PRIMARY KEY CLUSTERED 
(
Rollup_logID ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
GO 