ALTER TABLE [dbo].[RollupPlan] ADD  CONSTRAINT [PK_RollupPlan_PlanIdentifier] PRIMARY KEY CLUSTERED 
(
	[PlanIdentifier] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]


