ALTER TABLE [dbo].[RollupRunGroupLog] ADD  CONSTRAINT [PK_RollupRunGroupID] PRIMARY KEY CLUSTERED 
(
[RollupRunGroupID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
GO 