CREATE NONCLUSTERED INDEX [IDX_tbl_Summary_RskAdj_MMR_PymntYr_PlanID_PBP]
ON [rev].[tbl_Summary_RskAdj_MMR]
	(
	[PaymentYear] ASC
	)
INCLUDE ([PlanID],[HICN],[PaymStart],[SCC],[PBP],[HOSP])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
