CREATE NONCLUSTERED INDEX IDX_tbl_Summary_RskAdj_MMR_RskAdjAgeGrp
ON [rev].[tbl_Summary_RskAdj_MMR] 
(
[RskAdjAgeGrp] ASC
)
INCLUDE ([PlanID],[HICN],[PaymentYear],[PaymStart],[HOSP],[ESRD],[PartDRAFTMMR],[PartDRAFTProjected],[PartDAged])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO