CREATE NONCLUSTERED INDEX [IX_tbl_Summary_RskAdj_AltHICN__HICN__PlanID] ON [rev].[tbl_Summary_RskAdj_AltHICN]
(
[HICN] ,
[PlanID] 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
 ) 

