CREATE NONCLUSTERED INDEX [ix_tbl_RskAdj_EDS_Source_SrvEnddate] ON [rev].[tbl_Summary_RskAdj_EDS_Source]
(
	
	[ServiceEndDate] ASC
)
INCLUDE
( 	
	[HICN]
) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO