CREATE NONCLUSTERED INDEX [IX_EDSNewHCCPartC__ProcessRunId]
    ON [rev].[EDSNewHCCPartC]
(
    [HCC_PROCESSED_PCN]
  , [ProcessRunId])
    INCLUDE
(
    [EDSNewHCCPartCId]
  , [PCN_SubprojectId]
  , [FailureReason])
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF
        , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON )