CREATE NONCLUSTERED INDEX [IDX_EDS_DiagHCC_rollup_HICN_PatientControlNumber]
    ON [rev].[EDS_DiagHCC_rollup]
(
    [HICN]
  , [PatientControlNumber])
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF
        , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON )