ALTER TABLE Valuation.CalcPMHAndAttestationTotalsESRD ADD  CONSTRAINT PK_ValuationCalcPMHAndAttestationTotalsESRD PRIMARY KEY CLUSTERED 
(
[CalcPMHAndAttestationTotalsESRDId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF
, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON ) 


