ALTER TABLE Valuation.RptSummaryTotal ADD  CONSTRAINT PK_ValuationRptSummaryTotal PRIMARY KEY CLUSTERED 
(
[RptSummaryTotalId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF
, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON
 
) 



