ALTER TABLE Valuation.LogConfigSubProjectReviewName ADD  CONSTRAINT PK_ValuationLogConfigSubProjectReviewName PRIMARY KEY CLUSTERED 
(
[LogConfigSubProjectReviewNameId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF
, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON ) 


