ALTER TABLE [Valuation].[NewHCCPartC]
	ADD CONSTRAINT [PK_ValuationNewHCCPartC] PRIMARY KEY CLUSTERED 
	(
	[NewHCCPartCId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON ) 
 
