/*
Author:	Dianne Barba
TFS Request:	17141
Description:	Inserting values for RADVMemberRank
Create date:	01/03/2014

Modifications:

*/

insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (2, '01', 1)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (2, '02', 1)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (5, '01', 2)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (5, '02', 2)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (2, '10', 3)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (5, '10', 4)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (2, '20', 5)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (5, '20', 6)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (1, '01', 7)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (1, '02', 7)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (4, '01', 8)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (4, '02', 8)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (1, '10', 9)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (4, '10', 10)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (1, '20', 11)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (4, '20', 12)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (3, '01', 13)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (3, '02', 13)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (6, '01', 14)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (6, '02', 14)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (3, '10', 15)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (6, '10', 16)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (3, '20', 17)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (6, '20', 18)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (8, '01', 19)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (8, '02', 19)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (8, '10', 20)
insert into [dbo].[RADVMemberRank] (RADVStatusCodeID, ProviderTypeCode, RADVRank)
values (8, '20', 21)