
CREATE PROCEDURE [dbo].[spr_GetReportMenu]

@userid int, 
@groupid int = 0

AS

IF @groupid = 0 
BEGIN

	IF (SELECT Admin_User FROM tbl_Users WHERE User_ID = @userid) = 1
	BEGIN
		SELECT * FROM tbl_ReportGroups RG 
		INNER JOIN xref_ReportsReportGroups XRG
		ON XRG.REPORTGROUPID = RG.REPORTGROUPID 
		INNER JOIN tbl_Reports R
		ON R.REPORTID = XRG.REPORTID
		WHERE R.ACTIVE = 1
		ORDER BY RG.REPORTGROUPORDERBY, R.REPORTORDERBY
	END
	ELSE
	BEGIN
		SELECT * FROM tbl_ReportGroups RG 
		INNER JOIN xref_ReportsReportGroups XRG
		ON XRG.REPORTGROUPID = RG.REPORTGROUPID 
		INNER JOIN tbl_Reports R
		ON R.REPORTID = XRG.REPORTID
		WHERE R.ACTIVE = 1 AND (R.REPORTID IN (SELECT REPORTID FROM xref_User_Reports WHERE USER_ID = @userid) OR
		R.REPORTID IN (SELECT REPORTID FROM xref_ReportsReportGroups WHERE ReportGroupID IN (SELECT GroupID FROM xref_User_Reports WHERE USER_ID = @userid)))
		ORDER BY RG.REPORTGROUPORDERBY, R.REPORTORDERBY
	END


END
ELSE
BEGIN

	IF (SELECT Admin_User FROM tbl_Users WHERE User_ID = @userid) = 1
	BEGIN
		SELECT * FROM tbl_ReportGroups RG 
		INNER JOIN xref_ReportsReportGroups XRG
		ON XRG.REPORTGROUPID = RG.REPORTGROUPID 
		INNER JOIN tbl_Reports R
		ON R.REPORTID = XRG.REPORTID
		WHERE R.ACTIVE = 1 AND RG.REPORTGROUPID = @groupid
		--ORDER BY RG.REPORTGROUPORDERBY, R.REPORTORDERBY
		ORDER BY R.REPORT_DISPLAY_NAME
	END
	ELSE
	BEGIN
		SELECT * FROM tbl_ReportGroups RG 
		INNER JOIN xref_ReportsReportGroups XRG
		ON XRG.REPORTGROUPID = RG.REPORTGROUPID 
		INNER JOIN tbl_Reports R
		ON R.REPORTID = XRG.REPORTID
		WHERE R.ACTIVE = 1 AND (R.REPORTID IN (SELECT REPORTID FROM xref_User_Reports WHERE USER_ID = @userid) OR
		R.REPORTID IN (SELECT REPORTID FROM xref_ReportsReportGroups WHERE ReportGroupID IN (SELECT GroupID FROM xref_User_Reports WHERE USER_ID = @userid)))
		AND RG.REPORTGROUPID = @groupid
		--ORDER BY RG.REPORTGROUPORDERBY, R.REPORTORDERBY
		ORDER BY R.REPORT_DISPLAY_NAME
	END


END