ALTER TABLE [dbo].[CNClientBillingDetails] ADD CONSTRAINT [pk_CNClientBillingDetails] PRIMARY KEY CLUSTERED ([ClientBillingDetailID] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

