ALTER TABLE [dbo].[ExtractFile]
	ADD CONSTRAINT [PK_ExtractFile] PRIMARY KEY CLUSTERED ([ExtractFileID] ASC) 
	WITH (FILLFACTOR = 100 , ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);