ALTER TABLE [dbo].[CWFD_SubProjectMedicalRecords]
    ADD CONSTRAINT [PK_CWFD_SubProjectMedicalRecords] PRIMARY KEY CLUSTERED ([ID] ASC) WITH ( FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = ON, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



