ALTER TABLE [dbo].[lk_DCP_dates_RskAdj] ADD CONSTRAINT [PK_lk_DCP_dates_RskAdj_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
	WITH (
			PAD_INDEX = OFF
			,STATISTICS_NORECOMPUTE = OFF
			,SORT_IN_TEMPDB = OFF
			,IGNORE_DUP_KEY = OFF
			,ONLINE = OFF
			,ALLOW_ROW_LOCKS = ON
			,ALLOW_PAGE_LOCKS = ON
			)
