ALTER TABLE [dbo].[Raps_Accepted_rollup] ADD  CONSTRAINT [PK_Raps_Accepted_rollup_Raps_Accepted_rollupID] PRIMARY KEY CLUSTERED 
(
	[Raps_Accepted_rollupID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
