ALTER TABLE [dbo].[RAPS_RETURN_rollup] ADD  CONSTRAINT [PK_RAPS_RETURN_rollup_RAPS_RETURN_rollupID] PRIMARY KEY CLUSTERED 
(
	[RAPS_RETURN_rollupID] ASC
) WITH (PAD_INDEX = ON, FILLFACTOR = 100 ) ON [PRIMARY]