ALTER TABLE [dbo].[tbl_MMR_rollup]
ADD CONSTRAINT [PK_tbl_MMR_rollup]
    PRIMARY KEY CLUSTERED ([tbl_MMR_rollupID] ASC) 
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, 
		  IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF
		  )



