ALTER TABLE [dbo].[CWFDetails] 
ADD CONSTRAINT [PK_CWFDetails] PRIMARY KEY CLUSTERED 
([ID] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, 
		ALLOW_PAGE_LOCKS  = ON,FILLFACTOR = 100 ) 
		ON [PRIMARY]






