
ALTER TABLE [dbo].[tbl_MOR_Rollup] ADD CONSTRAINT [PK_tblMOR_Rollup] PRIMARY KEY CLUSTERED ([tbl_MOR_RollupID] ASC)
	 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON
            , ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100 )