ALTER TABLE [dbo].[tbl_AltHICN_rollup]
ADD CONSTRAINT [PK_tbl_AltHICN_rollup]
    PRIMARY KEY CLUSTERED ([tbl_AltHICN_rollupID] ASC) 
	WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, 
		  IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF
	     )
