ALTER TABLE rev.PartCNewHCCOutputSParameter
ADD CONSTRAINT [PK_PartCNewHCCOutputSParameterID] PRIMARY KEY CLUSTERED ([PartCNewHCCOutputSParameterID] ASC) 
WITH (FILLFACTOR = 100 , ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
