ALTER TABLE [rev].[EstRecvRskadjActivity] ADD CONSTRAINT [PK_EstRecvRskadjActivity_EstRecvRskadjActivityID] PRIMARY KEY CLUSTERED 
(
[EstRecvRskadjActivityID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 
 