ALTER TABLE [rev].[NewHCCActivity] ADD CONSTRAINT [PK_NewHCCActivity_NewHCCActivityID] PRIMARY KEY CLUSTERED 
(
[NewHCCActivityID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 