ALTER TABLE [rev].[EDS_DiagHCC_rollup]
ADD CONSTRAINT [PK_EDS_DiagHCC_rollup]
    PRIMARY KEY CLUSTERED
    (
        [EDS_DiagHCC_rollupID])
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF
        , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100 )

