ALTER TABLE [rev].[tbl_Summary_RskAdj_EDS]
ADD CONSTRAINT [PK_tbl_Summary_RskAdj_EDS]
    PRIMARY KEY CLUSTERED
    (
        [ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF
        , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON , FILLFACTOR = 100)