ALTER TABLE [rev].[tbl_Intermediate_EDS_INT] ADD  CONSTRAINT [PK_tbl_Intermediate_EDS_INT] PRIMARY KEY CLUSTERED 
(
	[tbl_Intermediate_EDS_INTId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON )


