
ALTER TABLE [rev].[tbl_EstRecv_EDS_DiagHCC_RskMod]
ADD CONSTRAINT [PK_tbl_EstRecv_EDS_DiagHCC_RskMod]
    PRIMARY KEY CLUSTERED
    (
        [EDS_DiagHCC_rollupID] )
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF
        , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON )