ALTER TABLE [rev].[tbl_Summary_RskAdj_Config] ADD  CONSTRAINT [PK_tbl_Summary_RskAdj_Config] PRIMARY KEY CLUSTERED 
(
[tbl_Summary_RskAdj_ConfigId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF
, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, FILLFACTOR = 100, ALLOW_PAGE_LOCKS  = ON ) 