ALTER TABLE [rev].[tbl_Intermediate_EDS] ADD  CONSTRAINT [PK_tbl_Intermediate_EDS] PRIMARY KEY CLUSTERED 
(
	[tbl_Intermediate_EDSId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON  ) 


