ALTER TABLE [rev].[tbl_Intermediate_RAPSMORCombined] ADD  CONSTRAINT [PK_tbl_Intermediate_RAPSMORCombined] PRIMARY KEY CLUSTERED 
(
[tbl_Intermediate_RAPSMORCombinedId] 
)WITH (PAD_INDEX  = ON, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF
, ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON ) 
