ALTER TABLE [rev].[tbl_Intermediate_RAPSMORCombined_INT] ADD  CONSTRAINT [PK_tbl_Intermediate_RAPSMORCombined_INT] PRIMARY KEY CLUSTERED 
(
[tbl_Intermediate_RAPSMORCombined_INTId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF
, SORT_IN_TEMPDB = ON , IGNORE_DUP_KEY = OFF
, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 


