ALTER TABLE [rev].[tbl_Intermediate_RAPS_INT] ADD  CONSTRAINT [PK_tbl_Intermediate_RAPS_INT] PRIMARY KEY CLUSTERED 
(
[tbl_Intermediate_RAPS_INTId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF
,  IGNORE_DUP_KEY = OFF
,  ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 
