ALTER TABLE [rev].[tbl_Summary_RskAdj_RAPS_Preliminary] ADD  CONSTRAINT [PK_tbl_Summary_RskAdj_RAPS_Preliminary] PRIMARY KEY CLUSTERED 
(
[tbl_Summary_RskAdj_RAPS_PreliminaryId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 
