ALTER TABLE [rev].[tbl_Intermediate_RAPSMORCombined_INTRank] ADD  CONSTRAINT [PK_tbl_Intermediate_RAPSMORCombined_INTRank] PRIMARY KEY CLUSTERED 
(
[tbl_Intermediate_RAPSMORCombined_INTRankId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF
, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF
, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON ) 


