ALTER TABLE [rev].[tbl_Intermediate_RAPS] ADD  CONSTRAINT [PK_tbl_Intermediate_RAPS] PRIMARY KEY CLUSTERED 
(
[tbl_Intermediate_RAPSId] 
)WITH (PAD_INDEX  = ON, STATISTICS_NORECOMPUTE  = OFF,  IGNORE_DUP_KEY = OFF
, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON ) 
