CREATE TABLE [dve].[_CriteriaColumnMap] (
	MapID			BIGINT	IDENTITY(-9223372036854775808,1) NOT NULL,
	GroupID			TINYINT	NOT NULL,
	isDefaultSrc	BIT		NOT NULL,
	isDefaultLcl	BIT		NOT NULL,
	SourceEntity	BIT		NOT NULL,
	LocalEntity		BIT		NOT NULL,
	ValueField		BIT		NOT NULL,
	RangeIDField	BIT		NOT NULL,
	isActive		BIT		NOT NULL,
	CONSTRAINT [PK__CriteriaColumnMap] PRIMARY KEY CLUSTERED (
		[MapID] ASC
	) WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS  = ON
	) ON [PRIMARY]
) ON [PRIMARY]