CREATE TABLE [dve].[_CriteriaTypeGroup] (
	TypeGroupID		BIGINT			IDENTITY(-9223372036854775808,1) NOT NULL,
	GroupID			TINYINT			NOT NULL,
	TypeID			INT				NOT NULL,
	CONSTRAINT [PK__CriteriaTypeGroup] PRIMARY KEY CLUSTERED (
		[TypeGroupID] ASC
	) WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS  = ON
	) ON [PRIMARY]
) ON [PRIMARY]