/****** Object:  Index [IX_CWFDetails_ProjectID]    Script Date: 05/07/2013 22:48:08 ******/
CREATE NONCLUSTERED INDEX [IX_CWFDetails_ProjectID] ON [dbo].[CWFDetails] 
(
	[ProjectID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
