CREATE NONCLUSTERED INDEX [IDX_tbl_RAPS_Detail_rollup_tbl_RAPS_Detail_ID_PlanIdentifier_RollupLoad]
ON [dbo].[tbl_RAPS_Detail_rollup] ([tbl_RAPS_Detail_ID],[PlanIdentifier], [RollupLoad])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, 
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
