CREATE NONCLUSTERED INDEX [IDX_Converted_MORD_Data_rollup_HICN_Payment_Month]
    ON [dbo].[Converted_MORD_Data_rollup]([HICN] ASC, [Payment_Month] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

