CREATE NONCLUSTERED INDEX [IDX_tbl_Member_Months_rollup_HICN_RA_Factor_Type]
    ON [dbo].[tbl_Member_Months_rollup]([HICN] ASC, [RA_Factor_Type] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

