CREATE NONCLUSTERED INDEX [IDX_tbl_Member_Months_rollup_HICN_PaymStart]
    ON [dbo].[tbl_Member_Months_rollup]([HICN] ASC, [PaymStart] ASC)
    INCLUDE([Plan]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

