CREATE NONCLUSTERED INDEX [IX_tbl_Summary_RskAdj_MMR_Alternate02] ON [dbo].[tbl_Summary_RskAdj_MMR] 
(
[HICN],
[SCC] ,
[PBP] ,
[PaymStart] ASC,
[PlanID] ASC,
[PartCRAFTProjected] ASC,
[PaymentYear] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100 ) 


