ALTER TABLE [dbo].[Organization]
    ADD CONSTRAINT [PK_Organization] PRIMARY KEY CLUSTERED ([OrganizationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

