ALTER TABLE [dbo].[HIMBaselineClientConfiguration]
	ADD CONSTRAINT [PK_dbo_HIMBaselineClientConfiguration_HIMBaselineClientConfigurationID] PRIMARY KEY CLUSTERED ([HIMBaselineClientConfigurationID] ASC) 
	WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);