ALTER TABLE [dbo].[EDSPlatformInstance]
    ADD CONSTRAINT [PK_EDSPlatformInstance] PRIMARY KEY CLUSTERED ([EDSPlatformInstanceID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

