ALTER TABLE [dbo].[OrganizationVendor]
    ADD CONSTRAINT [PK_OrganizationVendor] PRIMARY KEY CLUSTERED ([OrganizationVendorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

