ALTER TABLE [dbo].[RptOpsMetricsConfiguration]
	ADD CONSTRAINT [PK_RptOpsMetricsConfiguration] PRIMARY KEY CLUSTERED ([RptOpsMetricsConfigurationID] ASC) 
	WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);