CREATE TABLE [etl].[CohortImport](
	[CohortImportID] [int] IDENTITY(1,1) NOT NULL,
	[FileImportID] [int] NULL,
	[FileCreateDate] [datetime2](7) NOT NULL,
	[PlanMemberID] [varchar](18) NULL,
	[HICN] [varchar](24) NULL,
	[MemberEffectiveDate] [varchar](16) NULL,
	[MemberTerminationDate] [varchar](16) NULL,
	[MemberEnrollmentStatus] [varchar](2) NULL,
	[AutoEnrollmentIndicator] [varchar](2) NULL,
	[WritingAgentTaxIDNumber] [varchar](18) NULL,
	[GeneralAgentTaxIDNumber] [varchar](18) NULL,
	[EnrollmentSourceCode] [varchar](6) NULL,
	[EnrollmentChannelDescription] [varchar](40) NULL,
	[ContractNumber] [varchar](10) NULL,
	[CapOffice] [varchar](12) NULL,
	[CapOfficeEffectiveDate] [varchar](16) NULL,
	[CityOfResidence] [varchar](40) NULL,
	[StateOfResidence] [varchar](4) NULL,
	[ZipCode] [varchar](10) NULL,
	[ZipCodeExtension] [varchar](8) NULL,
	[ServiceArea] [varchar](8) NULL,
	[ServiceAreaDescription] [varchar](80) NULL,
	[FamilyPlanEffectiveDate] [varchar](16) NULL,
	[CompanyCode] [varchar](4) NULL,
	[GroupNumber] [varchar](32) NULL,
	[Location] [varchar](6) NULL,
	[PlanNumber] [varchar](10) NULL,
	[PBP] [varchar](6) NULL,
	[MemberType] [varchar](2) NULL,
	[Product] [varchar](6) NULL,
	[MedicareProduct] [varchar](8) NULL,
	[MedicalComponentCode] [varchar](10) NULL,
	[GroupPlanName] [varchar](60) NULL,
	[ExternalPlanName] [varchar](100) NULL,
	[PlanSponsorUniqueIDNumber] [varchar](32) NULL,
	[PlanSponsorName] [varchar](100) NULL,
	[ForecastedGroupPlanSponsorName] [varchar](100) NULL,
	[MedicalBenefitRatioGuarantee] [varchar](2) NULL,
	[CFOCode] [varchar](6) NULL,
	[CFODescription] [varchar](30) NULL,
	[LocalMarketCode] [varchar](12) NULL,
	[LocalMarketDescription] [varchar](50) NULL,
	[PlanMarketCode] [varchar](12) NULL,
	[PlanMarketDescription] [varchar](50) NULL,
	[RegionDescription] [varchar](30) NULL,
	[HMOGroupsMarketSegmentCode] [varchar](4) NULL,
	[CFOSubsegment] [varchar](20) NULL,
	[CFOSubsegmentDescription] [varchar](80) NULL,
	[FilePaymentMonth] [date] NULL,
	[CreateUserID] [varchar](30) NOT NULL,
	[CreateDateTime] [datetime2](7) NOT NULL,
	[CreateLoadID] [int] NOT NULL,
	[LoadID] [bigint] NULL,
	[LoadDate] [datetime] NULL)