CREATE TABLE etl.EstRecvDemographicsPartD
    (
      ID BIGINT IDENTITY(1, 1)
                NOT NULL ,
      PlanIdentifier INT NULL ,
      HPlanID VARCHAR(5) NULL ,
      HICN VARCHAR(12) NULL ,
      PaymentYear INT NOT NULL ,
      MYUFlag CHAR(1) NOT NULL ,
      PaymStart DATETIME NULL ,
      MonthRow INT NULL ,
      DateForFactors DATETIME NULL ,
      Gender INT NULL ,
      RskAdjAgeGrp CHAR(4) NULL ,
      AgeGrpID INT NULL ,
      PartDRAFTProjected CHAR(2) NULL ,
      PartDRAFTMMR CHAR(2) NULL ,
      ORECRestated INT NULL ,
      MedicaidRestated VARCHAR(4) NULL ,
      PartDRiskScoreMMR DECIMAL(19, 4) NULL ,
      SCC VARCHAR(10) NULL ,
      OOA CHAR(1) NULL ,
      PBP VARCHAR(6) NULL ,
      MABID MONEY NULL ,
      HOSP CHAR(1) NULL ,
      ISARUsed CHAR(1) NULL ,
      MonthsInLaggedDCP INT NULL ,
      MonthsInDCP INT NULL ,
      TotalPayment MONEY NULL ,
      TotalMAPaymentAmount MONEY NULL ,
      TotalPremiumYTD DECIMAL(20, 3) NULL ,
      MidYearUpdateFlag CHAR(1) NULL ,
      MidYearUpdateActual DECIMAL(20, 3) NULL ,
      MedicaidDualStatusCode CHAR(2) NULL ,
      Aged INT NULL ,
      BeneficiaryCurrentMedicaidStatus CHAR(1) NULL ,
      LowIncomeMultiplier DECIMAL(19, 4) NULL ,
      PartDBasicPremiumAmount DECIMAL(20, 3) NULL ,
      SourceType VARCHAR(4) NULL ,
      PartitionKey INT NOT NULL ,
      LoadDate DATETIME NULL,
	  UserID VARCHAR(128) NOT NULL,
	  PartDLowIncomeIndicator int NULL
    )


