CREATE TABLE [etl].[RAPSIntermediateForPartD]
    (
        RAPSIntermediateForPartDID BIGINT IDENTITY(1, 1) NOT NULL,
        PaymentYear SMALLINT NULL,
        ModelYear SMALLINT NULL,
        HICN VARCHAR(12) NULL,
        RAFT CHAR(3) NULL,
        HCC VARCHAR(50) NULL,
        HCCORIG VARCHAR(50) NULL,
        HCCNumber INT NULL,
        MinProcessBy DATETIME NULL,
        MinThru DATETIME NULL,
        MinProcessBySeqNum INT NULL,
        MinThruSeqNum INT NULL,
        Deleted CHAR(1) NULL,
        MinProcessbyDiagID INT NULL,
        MinThruDateDiagID INT NULL,
        MinProcessbyDiagCD VARCHAR(7) NULL,
        MinThruDateDiagCD VARCHAR(7) NULL,
        MinProcessByPCN VARCHAR(40) NULL,
        MinThruDatePCN VARCHAR(40) NULL,
        ProcessedPriorityThruDate DATETIME NULL,
        ThruPriorityProcessedBy DATETIME NULL,
        ProcessedPriorityFileID VARCHAR(18) NULL,
        ProcessedPriorityRAPSSourceID INT NULL,
        ProcessedPriorityProviderID VARCHAR(40) NULL,
        ProcessedPriorityRAC CHAR(1) NULL,
        ThruPriorityFileID VARCHAR(18) NULL,
        ThruPriorityRAPSSourceID INT NULL,
        ThruPriorityProviderID VARCHAR(40) NULL,
        ThruPriorityRAC CHAR(1) NULL,
        IMFFlag SMALLINT NULL,
        LoadDateTime DATETIME NOT NULL
    );