CREATE TABLE [etl].[tbl_Cohort] (
	[CohortId] [int] IDENTITY(1, 1) NOT NULL
	,[OrganizationID] [int] NULL
	,[MemberId] [varchar](18) NULL
	,[EffectiveDate] [datetime] NULL
	,[TermDate] [datetime] NULL
	,[HICN] [varchar](24) NULL
	,[CurrentHICN] [varchar](24) NULL
	,[PCP] [varchar](12) NULL
	,[CohortTag] [varchar](50) NULL
	,[Contract] [varchar](10) NULL
	,[PBP] [varchar](6) NULL
	,[FileName] [varchar](255) NULL
	,[GroupID] [varchar](255) NULL
	,[CohortDescription] [varchar](100) NULL
	,[PSUID] [varchar](32) NULL
	,[MemberEnrollmentStatus] [varchar](2) NULL
	,[AutoEnrollmentIndicator] [varchar](2) NULL
	,[WritingAgentTaxIDNumber] [varchar](18) NULL
	,[GeneralAgentTaxIDNumber] [varchar](18) NULL
	,[EnrollmentSourceCode] [varchar](6) NULL
	,[EnrollmentChannelDescription] [varchar](40) NULL
	,[CapOfficeEffectiveDate] [varchar](16) NULL
	,[CityOfResidence] [varchar](40) NULL
	,[StateOfResidence] [varchar](4) NULL
	,[ZipCode] [varchar](10) NULL
	,[ZipCodeExtension] [varchar](8) NULL
	,[FamilyPlanEffectiveDate] [varchar](16) NULL
	,[CompanyCode] [varchar](4) NULL
	,[Location] [varchar](6) NULL
	,[PlanNumber] [varchar](10) NULL
	,[Product] [varchar](6) NULL
	,[MedicalComponentCode] [varchar](10) NULL
	,[GroupPlanName] [varchar](60) NULL
	,[ExternalPlanName] [varchar](100) NULL
	,[ForecastedGroupPlanSponsorName] [varchar](100) NULL
	,[MedicalBenefitRatioGuarantee] [varchar](2) NULL
	,[CFOCode] [varchar](6) NULL
	,[CFODescription] [varchar](30) NULL
	,[PlanMarketCode] [varchar](12) NULL
	,[PlanMarketDescription] [varchar](50) NULL
	,[HMOGroupsMarketSegmentCode] [varchar](4) NULL
	,[FilePaymentMonth] [date] NULL
	,[Populated] [datetime] NULL
	,[LoadID] [bigint] NULL
	,[LoadDate] [datetime] NULL
	);