CREATE TABLE etl.QRAPSReconciliationExtractDetail (
	ID												BIGINT IDENTITY (1,1) NOT NULL
	,[Status]										VARCHAR(50) NULL
	,ValidationFailureID							SMALLINT NULL
	,ValidationFailureReason						VARCHAR(200) NULL
	,OriginalFileName								VARCHAR(255) NULL
	,SubmittedFileID								VARCHAR(10) NULL
	,PlanID											VARCHAR(5) NULL
	,LineOfBusiness									VARCHAR(100) NULL
	,PlanIdentifier									SMALLINT NULL
	,QRAPSRecordID									INT NULL
	,HICN											VARCHAR(50) NULL
	,From_Date1										VARCHAR(8) NULL
	,Thru_date1										VARCHAR(8) NULL
	,RAPSReturnHICNRejection						VARCHAR(6) NULL
	,RAPSReturnDOBRejection							VARCHAR(6) NULL
	,StartDate										DATETIME NULL
	,EndDate										DATETIME NULL
	,Diagnoses_1									VARCHAR(20) NULL
	,Delete_Ind1									CHAR(1) NULL
	,Diagnosis1Error1								VARCHAR(6) NULL
	,Diagnosis1Error2								VARCHAR(6) NULL
	,Diagnoses_2									VARCHAR(20) NULL
	,Delete_Ind2									CHAR(1) NULL
	,Diagnosis2Error1								VARCHAR(6) NULL
	,Diagnosis2Error2								VARCHAR(6) NULL
	,Diagnoses_3									VARCHAR(20) NULL
	,Delete_Ind3									CHAR(1) NULL
	,Diagnosis3Error1								VARCHAR(6) NULL
	,Diagnosis3Error2								VARCHAR(6) NULL
	,Diagnoses_4									VARCHAR(20) NULL
	,Delete_Ind4									CHAR(1) NULL
	,Diagnosis4Error1								VARCHAR(6) NULL
	,Diagnosis4Error2								VARCHAR(6) NULL
	,Diagnoses_5									VARCHAR(20) NULL
	,Delete_Ind5									CHAR(1) NULL
	,Diagnosis5Error1								VARCHAR(6) NULL
	,Diagnosis5Error2								VARCHAR(6) NULL
	,Diagnoses_6									VARCHAR(20) NULL
	,Delete_Ind6									CHAR(1) NULL
	,Diagnosis6Error1								VARCHAR(6) NULL
	,Diagnosis6Error2								VARCHAR(6) NULL
	,Diagnoses_7									VARCHAR(20) NULL
	,Delete_Ind7									CHAR(1) NULL
	,Diagnosis7Error1								VARCHAR(6) NULL
	,Diagnosis7Error2								VARCHAR(6) NULL
	,Diagnoses_8									VARCHAR(20) NULL
	,Delete_Ind8									CHAR(1) NULL
	,Diagnosis8Error1								VARCHAR(6) NULL
	,Diagnosis8Error2								VARCHAR(6) NULL
	,Diagnoses_9									VARCHAR(20) NULL
	,Delete_Ind9									CHAR(1) NULL
	,Diagnosis9Error1								VARCHAR(6) NULL
	,Diagnosis9Error2								VARCHAR(6) NULL
	,Diagnoses_10									VARCHAR(20) NULL
	,Delete_Ind10									CHAR(1) NULL
	,Diagnosis10Error2								VARCHAR(6) NULL
	,Diagnosis10Error1								VARCHAR(6) NULL
	,SubmitterID									VARCHAR(6) NULL
	,SubmittedFileName								VARCHAR(100) NULL
)