CREATE TABLE etl.RAPSLoadClaimsReconciliationExtractDetail (
	ID												BIGINT IDENTITY (1,1) NOT NULL
	,PlanIdentifier									SMALLINT NULL
	,Claim_Line_Number								VARCHAR(50) NULL
	,Plan_Claim_Number								VARCHAR(50) NULL
	,HICN											VARCHAR(25) NULL
	,Claim_ID										INT NULL
	,[Start_Date]									DATETIME NULL
	,[End_Date]										DATETIME NULL
	,Diagnoses_1									VARCHAR(20) NULL
	,Delete_Ind1									CHAR(1) NULL
	,Diagnoses_2									VARCHAR(20) NULL
	,Delete_Ind2									CHAR(1) NULL
	,Diagnoses_3									VARCHAR(20) NULL
	,Delete_Ind3									CHAR(1) NULL
	,Diagnoses_4									VARCHAR(20) NULL
	,Delete_Ind4									CHAR(1) NULL
	,Diagnoses_5									VARCHAR(20) NULL
	,Delete_Ind5									CHAR(1) NULL
	,Diagnoses_6									VARCHAR(20) NULL
	,Delete_Ind6									CHAR(1) NULL
	,Diagnoses_7									VARCHAR(20) NULL
	,Delete_Ind7									CHAR(1) NULL
	,Diagnoses_8									VARCHAR(20) NULL
	,Delete_Ind8									CHAR(1) NULL
	,Diagnoses_9									VARCHAR(20) NULL
	,Delete_Ind9									CHAR(1) NULL
	,Diagnoses_10									VARCHAR(20) NULL
	,Delete_Ind10									CHAR(1) NULL
	,Plan_Provider_ID								VARCHAR(50) NULL
	,ExclusionTypeID								TINYINT NULL
	,ExclusionType									VARCHAR(30) NULL
	,ExclusionReasonID								INT NULL
	,ExclusionReason								VARCHAR(80) NULL
	,Bill_Type										VARCHAR(4) NULL
	,Place_Of_Service								VARCHAR(15) NULL
	,Revenue_Code									VARCHAR(10) NULL
	,Procedure_Code									VARCHAR(15) NULL
	,Procedure_Code_Modifier						VARCHAR(15) NULL
	,From_Date1										VARCHAR(8) NULL
	,Thru_date1										VARCHAR(8) NULL
	,EXPORTED_FILEID								VARCHAR(10) NULL
	,RAPSStatusID									TINYINT NULL
	,OutboundFileID									VARCHAR(10) NULL
	,Plan_ID										VARCHAR(5) NULL
	,ClaimSource									VARCHAR(50) NULL
	,SplitFileName									VARCHAR(255) NULL
	,ClaimStatusID									TINYINT NULL
	,ClaimStatusDescription							VARCHAR(30) NULL
	,FileImportID									INT NULL
	,OriginalFileName								VARCHAR(255) NULL
	,OriginalFileDate								DATETIME NULL
	,[Status]										VARCHAR(50) NULL
	,RAPSReturnRejectReasonCodeHIC					VARCHAR(6) NULL
	,RAPSReturnRejectReasonCodeDOB					VARCHAR(6) NULL
	,DOB											DATETIME NULL
	,Diagnosis1Error1								VARCHAR(6) NULL
	,Diagnosis1Error2								VARCHAR(6) NULL
	,Diagnosis2Error1								VARCHAR(6) NULL
	,Diagnosis2Error2								VARCHAR(6) NULL
	,Diagnosis3Error1								VARCHAR(6) NULL
	,Diagnosis3Error2								VARCHAR(6) NULL
	,Diagnosis4Error1								VARCHAR(6) NULL
	,Diagnosis4Error2								VARCHAR(6) NULL
	,Diagnosis5Error1								VARCHAR(6) NULL
	,Diagnosis5Error2								VARCHAR(6) NULL
	,Diagnosis6Error1								VARCHAR(6) NULL
	,Diagnosis6Error2								VARCHAR(6) NULL
	,Diagnosis7Error1								VARCHAR(6) NULL
	,Diagnosis7Error2								VARCHAR(6) NULL
	,Diagnosis8Error1								VARCHAR(6) NULL
	,Diagnosis8Error2								VARCHAR(6) NULL
	,Diagnosis9Error1								VARCHAR(6) NULL
	,Diagnosis9Error2								VARCHAR(6) NULL
	,Diagnosis10Error2								VARCHAR(6) NULL
	,Diagnosis10Error1								VARCHAR(6) NULL
	,LineOfBusiness									VARCHAR(100) NULL
	,SubmitterID									VARCHAR(6) NULL
	,SubmittedFileName								VARCHAR(100) NULL
	,Pat_Control									NVARCHAR(20) NULL
	,Provd_Type1									NVARCHAR(2) NULL
	,ICD10Ind										VARCHAR(5) NULL
	,RAPS_Detail_ID									BIGINT NULL
	,EXPORTED_DATE									SMALLDATETIME NULL
	,Processed_By									SMALLDATETIME NULL
	,tbl_RAPS_Detail_rollup_HICN					NVARCHAR(25) NULL
	,Diag1											NVARCHAR(8) NULL
)