CREATE TABLE [dbo].[AltHICNXref] (
    [AltHICNXrefID] INT           IDENTITY (1, 1) NOT NULL,
    [FinalHICN]     VARCHAR (12)  NULL,
    [AltHICN]       VARCHAR (12)  NULL,
    [CreateDate]    SMALLDATETIME DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([AltHICNXrefID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

