CREATE TABLE [dbo].[CNCoreLogic] (
    [CNCoreLogicID]                            INT           IDENTITY (1, 1) NOT NULL,
    [ProjectDescription]                       VARCHAR (100)  NULL,
    [ProjectID]                                INT           NULL,
	[ProjectTypeID]                            INT           NULL,
    [ProjectType]                              VARCHAR (50)  NULL,
    [SubProjectID]                             INT           NULL,
    [SubProjectDescription]                    VARCHAR (100)  NULL,
    [SubProjectYOS]                            INT           NULL,
    [SubProjectYOS2]                           INT           NULL,
    [OrganizationID]                           INT           NULL,
    [OrganizationName]                         VARCHAR (255) NULL,
    [ProjectMedicalRecord]                     INT           NULL,
    [MedicalRecordID]                          INT           NULL,
    [MemberID]                                 INT           NULL,
    [HICN]                                     VARCHAR (12)  NULL,
    [MemberFirstName]                          VARCHAR (25)  NULL,
    [MemberLastName]                           VARCHAR (40)  NULL,
    [MemberDemographicSource]                  VARCHAR (6)   NULL,
    [ProviderID]                               VARCHAR (40)  NULL,
    [ProviderFirstName]                        VARCHAR (55)  NULL,
    [ProviderLastName]                         VARCHAR (100) NULL,
    [HRPSpecialtyCode]                         VARCHAR (63)  NULL,
    [ProviderGroupID]                          INT           NULL,
    [ProviderGroup]                            VARCHAR (60)  NULL,
    [Area]                                     VARCHAR (20)  NULL,
    [SubProjectWorkFlowTaskID]                 INT           NULL,
    [SubProjectWorkFlowTaskOrder]              INT           NULL,
    [WorkflowStepID]						   INT			 NULL,
    [WorkflowDisplayName]                      VARCHAR (140) NULL,
    [WorkflowStepName]                         VARCHAR (100) NULL,
	[ReleaseToCMS]							   INT			 NULL,
	[ReviewTypeID]                             INT			 NULL,
	[ReviewType]                               VARCHAR(30)   NULL,
    [PlanID]                                   VARCHAR (5)   NULL,
    [PBPCode]								   char (3)		 NULL,
    [SubProjectMedicalRecordID]                INT           NULL,
    [LogDate]                                  DATETIME      NULL,
    [SubProjectMedicalRecordStatusID]          INT           NULL,
    [SubProjectMedicalRecordStatusDescription] VARCHAR (50)  NULL,
    [ImageID]                                  INT           NULL,
    [Media]                                    VARCHAR (15)  NULL,
    [MedicalRecordRank]                        INT           NULL,
    [MemberRank]                               INT           NULL,
    [LoadDate]                                 DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CNCoreLogicID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

