CREATE TABLE [dbo].[CNCoreCodingReviewLogic] (
    [CNCoreCodingReviewLogicID]                   INT            IDENTITY (1, 1) NOT NULL,
    [ProjectDescription]                          VARCHAR (100)  NULL,
    [ProjectID]                                   INT            NULL,
    [SubProjectDescription]                       VARCHAR (100)   NULL,
    [SubProjectID]                                INT            NULL,
    [OnBehalfOfOrganizationID]					  INT			 NULL,
    [OrganizationID]                              INT            NULL,
    [ProjectMedicalRecordID]                      INT            NULL,
    [MedicalRecordID]                             INT            NULL,
    [MemberID]                                    INT            NULL,
    [HICN]                                        VARCHAR (12)   NULL,
    [ProviderID]                                  VARCHAR (40)   NULL,
    [PlanID]                                      VARCHAR (5)    NULL,
    [PBPCode]                                     CHAR (3)       NULL,
    [SubProjectMedicalRecordID]                   INT            NULL,
    [ImageID]									  INT            NULL,
    [WorkflowStepName]							  VARCHAR (100)  NULL,
	[WorkflowCompletedDateTime]					  datetime		 NULL,
    [CodedBy]                                     INT            NULL,
    [CoderFirstName]                              VARCHAR (50)   NULL,
    [CoderLastName]                               VARCHAR (50)   NULL,
    [CoderImageStatusDescription]                 VARCHAR (50)   NULL,
	[LastUpdateDateTime]						  datetime		 NULL,
    [CoderDailyCodingGoal]                        INT            NULL,
    [CoderAccuracyGoal]                           DECIMAL (5, 2) NULL,
    [CoderCodingTask]							  VARCHAR(5)	 NULL,
    [CoderMedicalRecordFailureReason]             VARCHAR (50)   NULL,
    [CoderMedicalRecordFailureComments]           VARCHAR (MAX)  NULL,
	[BegPage]				                      INT            NULL,
    [EndPage]                                     INT            NULL,
    [CoderDOSStart]                               DATE           NULL,
    [CoderDOSEnd]                                 DATE           NULL,
    [CoderYOS]                                    INT            NULL,
    [CoderIsRevenueGeneratingPartC]               BIT            NULL,
    [CoderIsRevenueGeneratingPartD]               BIT            NULL,
    [CoderICD9]                                   VARCHAR (6)    NULL,
    [CoderICDShortDescription]                    VARCHAR (50)   NULL,
	[CoderPartCHCCNumber]						  varchar(10)	 NULL,
	[CoderPartCHCCCMSDescription]				  varchar(100)	 NULL,
	[CoderPartDHCCNumber]						  varchar(10)	 NULL,
	[CoderPartDHCCCMSDescription]				  varchar(100)	 NULL,
    [CoderDiagnosisFailureReason]                 VARCHAR (50)   NULL,
    [CoderDiagnosisFailureComments]		          VARCHAR (200)  NULL,
    [CoderDOSFailureReason]			              VARCHAR (50)   NULL,
    [CoderDropHCC]                                BIT            NULL,
    [Result]                                      varchar(4)     NULL,
    [ReviewerID]                                  INT            NULL,
    [ReviewerFirstName]                           VARCHAR (50)   NULL,
    [ReviewerLastName]                            VARCHAR (50)   NULL,
   	[ReviewerImageStatusDescription]			  varchar(100)	 NULL,
    [ReviewerCodingTask]						  varchar(5)	 NULL,
	[ReviewerMedicalRecordFailureReason]		  varchar(50)	 NULL,
    [ReviewerMedicalRecordFailureComments]		  varchar(max)   NULL,
	[ReviewedDate]								  datetime		 NULL,
    [ReviewerDOSStart]                            DATE           NULL,
    [ReviewerDOSEnd]                              DATE           NULL,
    [ReviewerYOS]                                 INT            NULL,
	[ReviewerIsRevenueGeneratingPartC]			  bit			 NULL,
	[ReviewerIsRevenueGeneratingPartD]			  bit			 NULL,
	[ReviewerICD9]								  varchar(6)	 NULL,
    [ReviewerICDShortDescription]                 VARCHAR (50)   NULL,
	[ReviewerPartCHCCNumber]					  varchar(10)	 NULL,
	[ReviewerPartCHCCCMSDescription]			  varchar(100)	 NULL,
	[ReviewerPartDHCCNumber]					  varchar(10)	 NULL,
	[ReviewerPartDHCCCMSDescription]			  varchar(100)	 NULL,
	[ReviewerDiagnosisFailureReason]			  varchar(50)	 NULL,
	[ReviewerDiagnosisFailureComments]			  varchar(200)	 NULL,
	[ReviewerDOSFailureReason]					  varchar(50)	 NULL,
	[ReviewerDropHCC]							  bit			 NULL,
    [LoadDate]                                    DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([CNCoreCodingReviewLogicID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

