CREATE TABLE [dbo].[LogAutoProcessAction](
	[LogAutoProcessActionId] [int] IDENTITY(1,1) NOT NULL,
	[AutoProcessActionId] [int] NULL,
	[AutoProcessId] [int] NULL,
	[AutoProcessId_old] [int] NULL,
	[AutoProcessActionCatalogId] [int] NULL,
	[AutoProcessActionCatalogId_old] [int] NULL,
	[ClientId] [int] NULL,
	[ClientId_old] [int] NULL,
	[ByPlan] [bit] NULL,
	[ByPlan_old] [bit] NULL,
	[Phase] [decimal](18, 3) NULL,
	[Phase_old] [decimal](18, 3) NULL,
	[Priority] [int] NULL,
	[Priority_old] [int] NULL,
	[DependAutoProcessActionCatalogId] [int] NULL,
	[DependAutoProcessActionCatalogId_old] [int] NULL,
	[PopulateParameter] [bit] NULL,
	[PopulateParameter_old] [bit] NULL,
	[ActiveBDate] [date] NULL,
	[ActiveBDate_old] [date] NULL,
	[ActiveEDate] [date] NULL,
	[ActiveEDate_old] [date] NULL,
	[Added] [datetime] NULL,
	[Added_old] [datetime] NULL,
	[AddedBy] [varchar](257) NULL,
	[AddedBy_old] [varchar](257) NULL,
	[Edited]  [datetime] NULL,
	[EditedBy]  [varchar](257) NULL,
	[Action] [char](1) NULL
	
	)