Create Table RADVMemberDetail
(
		ID int identity,
		RADVMemberID int,
		ProviderNumber varchar (50),
		SubProjectMedicalRecordID int,
		SPMRLastUpdateDateTime datetime2,
		SPMRStatusID int,
		MedicalRecordRequestID int,
		MRRLastUpdateDateTime datetime2,
		ImageID int,
		ImageWorkflowStatusID int,
		ImageLastUpdateDateTime datetime2,
		ImageFilePath varchar (255),
		ImageFailureIssueID int,
		ImageFailureDescription varchar (50),
		ImageReviewStepID int,
		StartPage int,
		EndPage int,
		DOSStart date,
		DOSEnd date,
		ProviderTypeCD char (2),
		ProviderTypeDescription varchar(50),
		ICDCode varchar (10),
		ICDVersion char (2),
		HCCCode varchar (10),
		HCCPartID int,
		CodingDiagnosisID int,
		DateCoded datetime2,
		CodingStatusID int,
		CodingReviewStepID int,
		DiagnosisErrorID int,
		DOSErrorID int,
		FactorValue float,
		RADVStatusID int,
		RADVRank int,
		TotalValue money,
		AttestationReceivedDate datetime2,
		Comments varchar(200),
		CreationDateTime datetime2 default getdate()
)