CREATE TABLE [dbo].[RAPS_Detail_rollup] (
	[RAPS_Detail_rollupID] BIGINT identity (1, 1) NOT NULL,
	[PlanIdentifier]		SMALLINT NULL,
    [PLAN_ID]               VARCHAR (5)   NULL,
    [CLAIM_CONTROL_NUMBER]  VARCHAR (100) NULL,
    [HICN]                  VARCHAR (25)  NULL,
    [DATE_OF_SERVICE_START] SMALLDATETIME NULL,
    [DATE_OF_SERVICE_END]   SMALLDATETIME NULL,
    [PROVIDER_TYPE]         VARCHAR (5)   NULL,
    [DIAG1]                 VARCHAR (10)  NULL,
    [DIAG2]                 VARCHAR (10)  NULL,
    [DIAG3]                 VARCHAR (10)  NULL,
    [DIAG4]                 VARCHAR (10)  NULL,
    [DIAG5]                 VARCHAR (10)  NULL,
    [DIAG6]                 VARCHAR (10)  NULL,
    [DIAG7]                 VARCHAR (10)  NULL,
    [DIAG8]                 VARCHAR (10)  NULL,
    [DIAG9]                 VARCHAR (10)  NULL,
    [DIAG10]                VARCHAR (10)  NULL,
    [DELDIAG1]              VARCHAR (1)   NULL,
    [DELDIAG2]              VARCHAR (1)   NULL,
    [DELDIAG3]              VARCHAR (1)   NULL,
    [DELDIAG4]              VARCHAR (1)   NULL,
    [DELDIAG5]              VARCHAR (1)   NULL,
    [DELDIAG6]              VARCHAR (1)   NULL,
    [DELDIAG7]              VARCHAR (1)   NULL,
    [DELDIAG8]              VARCHAR (1)   NULL,
    [DELDIAG9]              VARCHAR (1)   NULL,
    [DELDIAG10]             VARCHAR (1)   NULL,
    [USER_UPLOADED_BY]      INT           NULL,
    [SOURCE]                VARCHAR (50)  NULL,
    [IMPORTED_DATE]         SMALLDATETIME NULL,
    [EXPORTED_FILEID]       VARCHAR (10)  NULL,
	[Source_ID]				int			  Null,
	[Provider_ID]			Varchar(40)	  Null,
	[Image_ID]				int			  Null,
	[Date_Of_Notification]	SmallDatetime Null,
	[In_Cluster]			bit			  Null,
	ICD char(1) NULL,
	RAC1 char(1) NULL,
	RAC2 char(1) NULL,
	RAC3 char(1) NULL,
	RAC4 char(1) NULL,
	RAC5 char(1) NULL,
	RAC6 char(1) NULL,
	RAC7 char(1) NULL,
	RAC8 char(1) NULL,
	RAC9 char(1) NULL,
	RAC10 char(1) NULL
	,RAPSDetailOverpaymentID INTEGER NULL
	,RAPS_Detail_ID BIGINT not null
	,MemberIDReceived VARCHAR(12) NULL
	,Claim_ID [int] NULL,
	RAPSDetailImportID [bigint] NULL,
	RAPSSourceTypeID [Tinyint] NULL,
	SPMRID [int] NULL,
	CNRAPSImportDetailID BIGINT NULL,
	[RollupLoad] [datetime] NULL 
)