CREATE TABLE [dbo].[RAPS_RETURN_rollup] (
	[RAPS_RETURN_rollupID] [Bigint] identity (1, 1) NOT NULL,
	[PlanIdentifier] SMALLINT      NULL,
    [Processed_By]   SMALLDATETIME NULL,
    [FileID]         VARCHAR (18)  NULL,
    [Record_id]      NVARCHAR (3)  NULL,
    [Seq_num1]       NVARCHAR (7)  NULL,
    [Seq_Error]      NVARCHAR (3)  NULL,
    [Pat_Control]    NVARCHAR (40) NULL,
    [HICN]           NVARCHAR (25) NULL,
    [Hic_Error]      NVARCHAR (3)  NULL,
    [DOB]            DATETIME      NULL,
    [DOB_Error]      NVARCHAR (3)  NULL,
    [Provd_Type1]    NVARCHAR (2)  NULL,
    [From_Date1]     SMALLDATETIME NULL,
    [Thru_date1]     SMALLDATETIME NULL,
    [Delete_Ind1]    NVARCHAR (1)  NULL,
    [Diag1]          NVARCHAR (8)  NULL,
    [DC_Filler1]     NVARCHAR (2)  NULL,
    [Diag1_Err1]     NVARCHAR (3)  NULL,
    [Diag1_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type2]    NVARCHAR (2)  NULL,
    [From_Date2]     SMALLDATETIME NULL,
    [Thru_Date2]     SMALLDATETIME NULL,
    [Delete_Ind_2]   NVARCHAR (1)  NULL,
    [Diag2]          NVARCHAR (8)  NULL,
    [DC_Filler2]     NVARCHAR (2)  NULL,
    [Diag2_Err1]     NVARCHAR (3)  NULL,
    [Diag2_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type3]    NVARCHAR (2)  NULL,
    [From_Date3]     SMALLDATETIME NULL,
    [Thru_Date3]     SMALLDATETIME NULL,
    [Delete_Ind3]    NVARCHAR (1)  NULL,
    [Diag3]          NVARCHAR (8)  NULL,
    [DC_Filler3]     NVARCHAR (2)  NULL,
    [Diag3_Err1]     NVARCHAR (3)  NULL,
    [Diag3_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type4]    NVARCHAR (2)  NULL,
    [From_Date4]     SMALLDATETIME NULL,
    [Thru_Date4]     SMALLDATETIME NULL,
    [Delete_Ind4]    NVARCHAR (1)  NULL,
    [Diag4]          NVARCHAR (8)  NULL,
    [DC_Filler4]     NVARCHAR (2)  NULL,
    [Diag4_Err1]     NVARCHAR (3)  NULL,
    [Diag4_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type5]    NVARCHAR (2)  NULL,
    [From_Date5]     SMALLDATETIME NULL,
    [Thru_Date5]     SMALLDATETIME NULL,
    [Delete_Ind5]    NVARCHAR (1)  NULL,
    [Diag5]          NVARCHAR (8)  NULL,
    [DC_Filler5]     NVARCHAR (2)  NULL,
    [Diag5_Err1]     NVARCHAR (3)  NULL,
    [Diag5_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type6]    NVARCHAR (2)  NULL,
    [From_Date6]     SMALLDATETIME NULL,
    [Thru_Date6]     SMALLDATETIME NULL,
    [Delete_Ind6]    NVARCHAR (1)  NULL,
    [Diag6]          NVARCHAR (8)  NULL,
    [DC_Filler6]     NVARCHAR (2)  NULL,
    [Diag6_Err1]     NVARCHAR (3)  NULL,
    [Diag6_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type7]    NVARCHAR (2)  NULL,
    [From_Date7]     SMALLDATETIME NULL,
    [Thru_date7]     SMALLDATETIME NULL,
    [Delete_Ind_7]   NVARCHAR (1)  NULL,
    [Diag7]          NVARCHAR (8)  NULL,
    [DC_Filler7]     NVARCHAR (2)  NULL,
    [Diag7_Err1]     NVARCHAR (3)  NULL,
    [Diag7_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type8]    NVARCHAR (2)  NULL,
    [From_Date8]     SMALLDATETIME NULL,
    [Thru_Date8]     SMALLDATETIME NULL,
    [Delete_Ind8]    NVARCHAR (1)  NULL,
    [Diag8]          NVARCHAR (8)  NULL,
    [DC_Filler8]     NVARCHAR (2)  NULL,
    [Diag8_Err1]     NVARCHAR (3)  NULL,
    [Diag8_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type9]    NVARCHAR (2)  NULL,
    [From_Date9]     SMALLDATETIME NULL,
    [Thru_date9]     SMALLDATETIME NULL,
    [Delete_Ind_9]   NVARCHAR (1)  NULL,
    [Diag9]          NVARCHAR (8)  NULL,
    [DC_Filler9]     NVARCHAR (2)  NULL,
    [Diag9_Err1]     NVARCHAR (3)  NULL,
    [Diag9_Err2]     NVARCHAR (3)  NULL,
    [Provd_Type10]   NVARCHAR (2)  NULL,
    [From_Date10]    SMALLDATETIME NULL,
    [Thru_Date10]    SMALLDATETIME NULL,
    [Delete_Ind10]   NVARCHAR (1)  NULL,
    [Diag10]         NVARCHAR (8)  NULL,
    [DC_Filler10]    NVARCHAR (2)  NULL,
    [Diag10_Err1]    NVARCHAR (3)  NULL,
    [Diag10_Err2]    NVARCHAR (3)  NULL,
    [Corrected_HICN] NVARCHAR (25) NULL,
    [Filler]         NVARCHAR (75) NULL,
    [IMPORTED_DATE]  SMALLDATETIME NULL,
	ICD char(1) NULL,
	RAC1 char(1) NULL,
	RAC_Error1 varchar(3) NULL,
	RAC2 char(1) NULL,
	RAC_Error2 varchar(3) NULL,
	RAC3 char(1) NULL,
	RAC_Error3 varchar(3) NULL,
	RAC4 char(1) NULL,
	RAC_Error4 varchar(3) NULL,
	RAC5 char(1) NULL,
	RAC_Error5 varchar(3) NULL,
	RAC6 char(1) NULL,
	RAC_Error6 varchar(3) NULL,
	RAC7 char(1) NULL,
	RAC_Error7 varchar(3) NULL,
	RAC8 char(1) NULL,
	RAC_Error8 varchar(3) NULL,
	RAC9 char(1) NULL,
	RAC_Error9 varchar(3) NULL,	
	RAC10 char(1) NULL,
	RAC_Error10 varchar(3) NULL,
	RAPSReturnBRecordsID int NULL, 
    [UploadID] INT NULL
)