
CREATE TABLE DBO.RptClientPcnStrings
(
RptClientPcnStringsID INT IDENTITY(1,1) NOT NULL,
IDENTIFIER VARCHAR(100),
CLIENT_DB VARCHAR(100),
PAYMENT_YEAR INT,
PROJECT VARCHAR(100),
PCN_STRING VARCHAR(100),
LASTUPDATEDTM DATETIME,
ACTIVE CHAR(1),
TERMDATE DATE
)


