CREATE TABLE [dbo].[SubmissionBalancingDetail](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOB] [varchar](10) NOT NULL,
	[ProjectID] [int] NOT NULL,
	[ProjectDescription] [varchar](85) NULL,
	[SubProjectID] [int] NOT NULL,
	[SubProjectDescription] [varchar](85) NULL,
	[ProjectReportingYear] [int] NULL,
	[PlanID] [varchar](40) NULL,
	[MemberHICN] [varchar](50) NULL,
	[MemberNumber] [varchar](50) NULL,
	[ProviderType] [varchar](50) NULL,
	[DOSStartDt] [date] NULL,
	[DOSEndDt] [date] NULL,
	[DiagnosisCode] [varchar](8) NOT NULL,
	[DiagnosisID] [int] NOT NULL,
	[DiagnosisStatusID] [tinyint] NOT NULL,
	[DiagnosisStatusDescription] [varchar](50) NULL,
	[DiagnosisCodedDate] [datetime] NOT NULL,
	[ClusterKey] [varbinary](8000) NULL,
	[ClusterRank] [bigint] NULL,
	[SubProjectMedicalRecordID] [int] NULL,
	[MedicalRecordImageWorkFlowID] [int] NULL,
	[MedicalRecordImageID] [int] NULL,
	[ListChaseID] [varchar](50) NULL,
	[CNMemberID] [int] NULL,
	[CodingCompleteDate] [datetime2](7) NULL,
	[CNLastSyncDate] [datetime2](7) NULL,
	[SubmittedFileName] [varchar](10) NULL,
	[DateSubmitted] [smalldatetime] NULL,
	[RAPSStatusID] [tinyint] NULL,
	[RAPSSubmissionRecordStatus] [varchar](25) NULL,
	[SubmissionPlanID] [varchar](10) NULL,
	[SubmissionHICN] [nvarchar](25) NULL,
	[SubmissionFromDate] [varchar](8) NULL,
	[SubmissionThruDate] [varchar](8) NULL,
	[SubmittedDiagnosisCode] [nvarchar](8) NULL,
	[SubmissionSource] bit NULL,
	[SubmissionLastSyncDate] [datetime2](7) NULL,
	[MRAExtractPlanID] [varchar](10) NULL,
	[MRAExtractHICN] [nvarchar](25) NULL,
	[MRAExtractFromDate] [varchar](20) NULL,
	[MRAExtractThruDate] [varchar](20) NULL,
	[MRAExtractDiagnosisCode] [nvarchar](8) NULL,
	[MRAExtractSPMRID] int,
	[MRAExtractImageID] int,
	[MRAChaseID] varchar(50),
	[MRAExtractSource] bit NULL,
	[MRAExtractLastSyncDate] [datetime2](7) NULL,
	[CRAExtractPlanID] [varchar](10) NULL,
	[CRAExtractMemberNumber] [nvarchar](25) NULL,
	[CRAExtractFromDate] [varchar](20) NULL,
	[CRAExtractThruDate] [varchar](20) NULL,
	[CRAExtractDiagnosisCode] [nvarchar](8) NULL,
	[CRAExtractSPMRID] int,
	[CRAExtractImageID] int,
	[CRAChaseID] varchar(50),
	[CRAExtractSource] bit NULL,
	[CRAExtractLastSyncDate] [datetime2](7) NULL

)