CREATE TABLE [dbo].[tbl_Member_Months_Plan_rollup](
	tbl_Member_Months_Plan_rollupID	int Identity NOT NULL,
	PlanIdentifier			smallint Not Null,
	[PLANID] [varchar](8) NULL,
	[PAYMSTART] [smalldatetime] NULL,
	[HICN] [varchar](15) NULL,
	[LAST] [varchar](50) NULL,
	[FIRST] [varchar](50) NULL,
	[MI] [varchar](3) NULL,
	[DOB] [datetime] NULL,
	[GENDER] [nvarchar](1) NULL,
	[SSN] [nvarchar](13) NULL,
	[MEMBERID] [varchar](25) NULL,
	[COUNTY_OF_RESIDENCE] [varchar](50) NULL,
	[MEDICAID_STATUS] [nvarchar](1) NULL,
	[DISABILITY_STATUS] [nvarchar](1) NULL,
	[PBP] [varchar](25) NULL,
	[WITHHOLD_OPTION] [nvarchar](1) NULL,
	[Low_Income_Cost_Sharing] [nvarchar](1) NULL,
	[LIS_SUBSIDY] [nvarchar](3) NULL,
	[ESRD] [nvarchar](1) NULL,
	[HOSPICE] [nvarchar](1) NULL,
	[WORKING_AGED] [nvarchar](1) NULL,
	[INSTITUTIONAL] [nvarchar](1) NULL,
	[GROUP] [varchar](20) NULL,
	[ADDRESS1] [varchar](100) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](2) NULL,
	[ZIP] [varchar](5) NULL,
	[PLAN_RISK_SCORE_C] [decimal](19, 4) NULL,
	[PLAN_RISK_SCORE_D] [decimal](19, 4) NULL,
	[POPULATED] [smalldatetime] NULL,
	[Phone] [varchar](14) NULL,
	[MemberIDReceived] [varchar](12) NULL
)