CREATE TABLE [dbo].[tbl_MMR_rollup] (
    [tbl_MMR_rollupID]                                        INT                IDENTITY (1, 1) NOT NULL,
    [PlanIdentifier]                                          SMALLINT           NOT NULL,
    [MMRID]                                                   INT                NOT NULL,
    [Plan]                                                    NVARCHAR (5)       NULL,
    [RunDate]                                                 SMALLDATETIME      NULL,
    [PaymentDate]                                             NVARCHAR (6)       NULL,
    [HICN]                                                    NVARCHAR (12)      NULL,
    [Surname]                                                 NVARCHAR (20)      NULL,
    [FirstI]                                                  NVARCHAR (12)      NULL,
    [MI]                                                      NVARCHAR (1)       NULL,
    [Sex]                                                     NVARCHAR (1)       NULL,
    [DOB]                                                     DATETIME           NULL,
    [AgeGrp]                                                  NVARCHAR (4)       NULL,
    [SCC]                                                     NVARCHAR (5)       NULL,
    [OOA]                                                     NVARCHAR (1)       NULL,
    [PartAEnt]                                                NVARCHAR (1)       NULL,
    [PartBent]                                                NVARCHAR (1)       NULL,
    [Hosp]                                                    NVARCHAR (1)       NULL,
    [ESRD]                                                    NVARCHAR (1)       NULL,
    [WA]                                                      NVARCHAR (1)       NULL,
    [Institutional]                                           NVARCHAR (1)       NULL,
    [NHInd]                                                   NVARCHAR (1)       NULL,
    [Medicaid]                                                NVARCHAR (1)       NULL,
    [Long_Term_Institutional]                                 NVARCHAR (1)       NULL,
    [MedicAddOn]                                              NVARCHAR (1)       NULL,
    [PIPDCG]                                                  NVARCHAR (2)       NULL,
    [DefaultInd]                                              NVARCHAR (1)       NULL,
    [RskadjFctrA]                                             DECIMAL (19, 4)    NULL,
    [RskadjFctrB]                                             DECIMAL (19, 4)    NULL,
    [AdjPtB]                                                  SMALLINT           NULL,
    [AdjPtA]                                                  SMALLINT           NULL,
    [AdjReason]                                               NVARCHAR (2)       NULL,
    [DemoPymtA]                                               SMALLMONEY         NULL,
    [DemoPymtB]                                               SMALLMONEY         NULL,
    [RiskPymtA]                                               SMALLMONEY         NULL,
    [RiskPymtB]                                               SMALLMONEY         NULL,
    [BlendedPayA]                                             SMALLMONEY         NULL,
    [ESRD_MSP_FLAG]                                           NVARCHAR (1)       NULL,
    [BlendPayB]                                               SMALLMONEY         NULL,
    [TotalPayment]                                            SMALLMONEY         NULL,
    [PaymStart]                                               SMALLDATETIME      NULL,
    [PaymEnd]                                                 SMALLDATETIME      NULL,
    [CongHrtFail]                                             NVARCHAR (2)       NULL,
    [RskAdjAgeGrp]                                            NVARCHAR (4)       NULL,
    [PrevDisbRatio]                                           SMALLINT           NULL,
    [2002chfflag]                                             NVARCHAR (1)       NULL,
    [Beneficiary_Dual_Part_D_Enrollment]                      NVARCHAR (1)       NULL,
    [pbp]                                                     NVARCHAR (3)       NULL,
    [race]                                                    NVARCHAR (1)       NULL,
    [RA_Factor_Type]                                          NVARCHAR (2)       NULL,
    [Frailty]                                                 NVARCHAR (1)       NULL,
    [OREC]                                                    NVARCHAR (1)       NULL,
    [Lag_Ind]                                                 NVARCHAR (1)       NULL,
    [Future_Flag]                                             NVARCHAR (1)       NULL,
    [Low_Income_Premium_Subsidy]                              SMALLMONEY         NULL,
    [Segment_ID]                                              NVARCHAR (3)       NULL,
    [Enrollment_Source]                                       NVARCHAR (1)       NULL,
    [EGHP_Flag]                                               NVARCHAR (1)       NULL,
    [Part_C_Basic_Premium_Part_A_Amount]                      SMALLMONEY         NULL,
    [Part_C_Basic_Premium_Part_B_Amount]                      SMALLMONEY         NULL,
    [Rebate_for_Part_A_Cost_Sharing_Reduction]                SMALLMONEY         NULL,
    [Rebate_for_Part_B_Sharing_Reduction]                     SMALLMONEY         NULL,
    [Rebate_for_Other_Part_A_Mandatory_Supplemental_Benefits] SMALLMONEY         NULL,
    [Rebate_for_Other_Part_B_Mandatory_Supplemental_Benefits] SMALLMONEY         NULL,
    [Rebate_for_Part_B_Premium_Reduction_Part_A_Amount]       SMALLMONEY         NULL,
    [Rebate_for_Part_B_Premium_Reduction_Part_B_Amount]       SMALLMONEY         NULL,
    [Rebate_for_Part_D_Supplemental_Benefits_Part_A_Amount]   SMALLMONEY         NULL,
    [Rebate_for_Part_D_Supplemental_Benefits_Part_B_Amount]   SMALLMONEY         NULL,
    [Total_Part_A_MA_Payment]                                 SMALLMONEY         NULL,
    [Total_Part_B_MA_Payment]                                 SMALLMONEY         NULL,
    [Total_MA_Payment_Amount]                                 SMALLMONEY         NULL,
    [Part_D_RA_Factor]                                        DECIMAL (19, 4)    NULL,
    [Part_D_Low_Income_Indicator]                             NVARCHAR (1)       NULL,
    [Part_D_Low_Income_Multiplier]                            DECIMAL (19, 2)    NULL,
    [Part_D_Long_Term_Institutional_Indicator]                NVARCHAR (1)       NULL,
    [Part_D_Long_Term_Institutional_Multiplier]               DECIMAL (19, 2)    NULL,
    [Rebate_for_Part_D_Basic_Premium_Reduction]               SMALLMONEY         NULL,
    [Part_D_Basic_Premium_Amount]                             SMALLMONEY         NULL,
    [Part_D_Direct_Subsidy_Payment_Amount]                    SMALLMONEY         NULL,
    [Reinsurance_Subsidy_Amount]                              SMALLMONEY         NULL,
    [Low_Income_Subsidy_Cost_Sharing_Amount]                  SMALLMONEY         NULL,
    [Total_Part_D_Payment]                                    SMALLMONEY         NULL,
    [Number_of_Payment_Adjustment_Months_Part_D]              SMALLINT           NULL,
    [Pace_Premium_Add_On]                                     SMALLMONEY         NULL,
    [Pace_Cost_Sharing_Add_On]                                SMALLMONEY         NULL,
    [MSA_Part_A_Deposit_Amount]                               MONEY              NULL,
    [MSA_Part_B_Deposit_Amount]                               MONEY              NULL,
    [MSA_Deposit_Months]                                      INT                NULL,
    [Beneficiary_Current_Medicaid_Status]                     CHAR (1)           NULL,
    [DeMinimis]                                               CHAR (1)           NULL,
    [Part_C_Frailty_Score_Factor]                             DECIMAL (19, 4)    NULL,
    [Imported_Date]                                           SMALLDATETIME      NULL,
    [AgedDisabledMSP]                                         CHAR (1)           NULL,
    [MSPFactor]                                               DECIMAL (9, 4)     NULL,
    [MSPReductionAdjAmountPartA]                              SMALLMONEY         NULL,
    [MSPReductionAdjAmountPartB]                              SMALLMONEY         NULL,
    [Medicaid_Dual_Status_Code]                               VARCHAR (2) SPARSE NULL,
    [Part_D_Coverage_Gap_Discount_Amount]                     SMALLMONEY         NULL,
    [Part_D_RA_Factor_Type]                                   VARCHAR (2) SPARSE NULL,
    [Default_Part_D_Risk_Factor_Code]                         VARCHAR (1)        NULL,
	[MemberIDReceived]										  VARCHAR(12)        NULL
);

