
CREATE TABLE [dbo].[tbl_EstRecv_RiskFactorsRAPS](
	[PlanID] [int] NULL,
	[HICN] [varchar](12) NULL,
	[PaymentYear] [int] NULL,
	[PaymStart] [datetime] NULL,
	[Model_Year] [int] NULL,
	[Factor_category] [varchar](20) NULL,
	[Factor_Desc] [varchar](50) NULL,
	[Factor] [decimal](20, 4) NULL,
	[RAFT] [varchar](3) NULL,
	[HCC_Number] [int] NULL,
	[Min_ProcessBy] [datetime] NULL,
	[Min_ThruDate] [datetime] NULL,
	[Min_ProcessBy_SeqNum] [int] NULL,
	[Min_ThruDate_SeqNum] [int] NULL,
	Min_Processby_DiagCD	varchar(7) NULL,	 
	Min_ThruDate_DiagCD	varchar(7) NULL,	
	Min_ProcessBy_PCN	varchar(40) NULL,	
	Min_ThruDate_PCN	varchar(40) NULL,
	processed_priority_thru_date datetime null,
	thru_priority_processed_by datetime null,
	RAFT_ORIG Varchar(2) NULL,
	[Processed_Priority_FileID] [varchar](18) NULL,
	[Processed_Priority_RAPS_Source_ID] [int] NULL,
	[Processed_Priority_Provider_ID] [varchar](40) NULL,
	[Processed_Priority_RAC] [varchar](1) NULL,
	[Thru_Priority_FileID] [varchar](18) NULL,
	[Thru_Priority_RAPS_Source_ID] [int] NULL,
	[Thru_Priority_Provider_ID] [varchar](40) NULL,
	[Thru_Priority_RAC] [varchar](1) NULL,
	[IMFFlag] [smallint] NULL,
	[Factor_Desc_ORIG] [varchar](50) NULL,
	[Factor_Desc_EstRecev] [VARCHAR](50) NULL
) 
