CREATE TABLE [dbo].[tbl_Member_Months_rollup] (
    [tbl_Member_Months_rollupID]                              INT                IDENTITY (1, 1) NOT NULL,
    [PlanIdentifier]                                          SMALLINT           NOT NULL,
    [Plan]                                                    NVARCHAR (5)       NULL,
    [RunDate]                                                 SMALLDATETIME      NULL,
    [HICN]                                                    NVARCHAR (12)      NULL,
    [AgeGrp]                                                  NVARCHAR (4)       NULL,
    [DOB]                                                     DATETIME           NULL,
    [ESRD]                                                    NVARCHAR (1)       NULL,
    [FirstI]                                                  NVARCHAR (12)      NULL,
    [Hosp]                                                    NVARCHAR (1)       NULL,
    [Institutional]                                           NVARCHAR (1)       NULL,
    [Low_Income_Premium_Subsidy]                              SMALLMONEY         NULL,
    [Low_Income_Subsidy_Cost_Sharing_Amount]                  SMALLMONEY         NULL,
    [MedicAddOn]                                              NVARCHAR (1)       NULL,
    [Medicaid]                                                NVARCHAR (1)       NULL,
    [OOA]                                                     NVARCHAR (1)       NULL,
    [OREC]                                                    NVARCHAR (1)       NULL,
    [Part_D_Basic_Premium_Amount]                             SMALLMONEY         NULL,
    [Part_D_Direct_Subsidy_Payment_Amount]                    SMALLMONEY         NULL,
    [Part_D_Low_Income_Indicator]                             NVARCHAR (1)       NULL,
    [Part_D_Low_Income_Multiplier]                            DECIMAL (19, 2)    NULL,
    [Part_D_RA_Factor]                                        DECIMAL (19, 4)    NULL,
    [Part_D_RA_Factor_Type]                                   VARCHAR (2) SPARSE NULL,
    [PaymStart]                                               SMALLDATETIME      NULL,
    [PaymEnd]                                                 SMALLDATETIME      NULL,
    [pbp]                                                     NVARCHAR (3)       NULL,
    [RA_Factor_Type]                                          NVARCHAR (2)       NULL,
    [Rebate_for_Other_Part_A_Mandatory_Supplemental_Benefits] SMALLMONEY         NULL,
    [Rebate_for_Other_Part_B_Mandatory_Supplemental_Benefits] SMALLMONEY         NULL,
    [Rebate_for_Part_A_Cost_Sharing_Reduction]                SMALLMONEY         NULL,
    [Rebate_for_Part_B_Premium_Reduction_Part_A_Amount]       SMALLMONEY         NULL,
    [Rebate_for_Part_B_Premium_Reduction_Part_B_Amount]       SMALLMONEY         NULL,
    [Rebate_for_Part_B_Sharing_Reduction]                     SMALLMONEY         NULL,
    [Rebate_for_Part_D_Basic_Premium_Reduction]               SMALLMONEY         NULL,
    [Rebate_for_Part_D_Supplemental_Benefits_Part_A_Amount]   SMALLMONEY         NULL,
    [Rebate_for_Part_D_Supplemental_Benefits_Part_B_Amount]   SMALLMONEY         NULL,
    [Reinsurance_Subsidy_Amount]                              SMALLMONEY         NULL,
    [RiskPymtA]                                               SMALLMONEY         NULL,
    [RiskPymtB]                                               SMALLMONEY         NULL,
    [RskAdjAgeGrp]                                            NVARCHAR (4)       NULL,
    [RskadjFctrA]                                             DECIMAL (19, 4)    NULL,
    [RskadjFctrB]                                             DECIMAL (19, 4)    NULL,
    [SCC]                                                     NVARCHAR (5)       NULL,
    [Sex]                                                     NVARCHAR (1)       NULL,
    [Surname]                                                 NVARCHAR (20)      NULL,
    [Total_MA_Payment_Amount]                                 SMALLMONEY         NULL,
    [Total_Part_D_Payment]                                    SMALLMONEY         NULL,
    [TotalPayment]                                            SMALLMONEY         NULL,
    [WA]                                                      NVARCHAR (1)       NULL,
	[Long_Term_Institutional]								  NVARCHAR (1)       NULL,
	[DefaultInd]											  NVARCHAR (1)       NULL,
	[Beneficiary_Current_Medicaid_Status]					  CHAR(1)			 NULL,
	[Populated]												  SMALLDATETIME      NULL,
	[CongHrtFail]											  NVARCHAR(2)		 NULL,
	[Default_Part_D_Risk_Factor_Code]						  VARCHAR(1)		 NULL,
	[EGHP_Flag]												  NVARCHAR(1)		 NULL,
	[ESRD_MSP_FLAG]											  NVARCHAR(1)		 NULL,
	[LIS_Premium_Subsidy]									  SMALLMONEY		 NULL,
	[Medicaid_Dual_Status_Code]								  VARCHAR(2)		 NULL,
	[MSPFactor]												  DECIMAL (9, 4)	 NULL,
	[Pace_Cost_Sharing_Add_On]								  SMALLMONEY		 NULL,
	[Pace_Premium_Add_On]									  SMALLMONEY		 NULL,
	[Part_A_Monthly_Payment_Rate]							  SMALLMONEY		 NULL,
	[Part_B_Monthly_Payment_Rate]							  SMALLMONEY		 NULL,
	[Part_C_Basic_Premium_Part_A_Amount]					  SMALLMONEY		 NULL,
	[Part_C_Basic_Premium_Part_B_Amount]					  SMALLMONEY		 NULL,
	[Part_D_Coverage_Gap_Discount_Amount]					  SMALLMONEY		 NULL,
	[Part_D_Long_Term_Institutional_Indicator]				  NVARCHAR(1)		 NULL,
	[Part_D_Long_Term_Institutional_Multiplier]				  DECIMAL (19, 2)    NULL,
	[Part_D_Monthly_Payment_Rate]							  SMALLMONEY		 NULL,
	[PartAEnt]												  NVARCHAR(1)		 NULL,
	[PartBent]												  NVARCHAR(1)		 NULL,
	[PrevDisbRatio]											  SMALLMONEY		 NULL,
	[Total_Part_A_MA_Payment]								  SMALLMONEY		 NULL,
	[Total_Part_B_MA_Payment]								  SMALLMONEY		 NULL,
	[MemberIDReceived]	                                      VARCHAR(12)        NULL
);

