Create Table dbo.tbl_Transaction_Reply_rollup
   (tbl_Transaction_Reply_rollupID				INT					IDENTITY	NOT NULL,
    PlanIdentifier								SMALLINT						NOT NULL,
	Plan_ID										VARCHAR(5)						NULL,
	RecordID 									INT								NOT NULL,
	HICN										VARCHAR(12)						NULL,
	Transaction_Date							VARCHAR(8)						NULL,
	Application_Date							VARCHAR(8)						NULL,
	Transaction_Reply_Code						VARCHAR(3)						NULL,
	Election_Type								VARCHAR(1)						NULL,
	PBP											VARCHAR(3)						NULL,
	Disenrollment_Reason_Code					VARCHAR(2)						NULL,
    Transaction_Reply_Detail                    VARCHAR(12)						NULL,
	Transaction_Effective_Date					VARCHAR(8)						NULL,
	Transaction_Type_Code						VARCHAR(2)						NULL,
	Surname										VARCHAR(12)						NULL,
	First_Name									VARCHAR(7)						NULL,
	Middle_Name									VARCHAR(1)						NULL,
	Sex_Code									VARCHAR(1)						NULL,
	DOB											VARCHAR(8)						NULL,
	Medicaid_Indicator							VARCHAR(1)						NULL,
	State_Code									VARCHAR(2)						NULL,
	County_Code									VARCHAR(3)						NULL,
	Disability_Indicator						VARCHAR(1)						NULL,
	Hospice_Indicator							VARCHAR(1)						NULL,
	Institutional_NHC_Indicator					VARCHAR(1)						NULL,
	ESRD_Indicator								VARCHAR(1)						NULL,
	WA_Indicator								VARCHAR(1)						NULL,
	Prior_PBP									VARCHAR(3)						NULL, 
	Prev_Part_D_Contract_PBP					VARCHAR(8)						NULL,
	Part_D_Opt_Out_Flag							VARCHAR(1)						NULL,	
    Enrollee_Type_Flag_PBP_Level                VARCHAR(1)						NULL,
    Enrollment_Period_Descriptor                VARCHAR(1)						NULL,
    Populated                                   SMALLDATETIME					NULL,
    MemberIDReceived	                        VARCHAR(12)					    NULL
	)