CREATE TABLE [dbo].[tbl_PDE_rollup](
	tbl_PDE_rollupID					int Identity NOT NULL,
	PlanIdentifier						smallint Not Null,
	HICN								varchar(20) NULL,
	QUANTITY_DISPENSED					varchar(10) NULL,
	PRODUCT_SERVICE_ID					varchar(19) NULL,
	DATE_OF_SERVICE						smalldatetime NULL,
	ADJUSTMENT_DELETIONCODE				varchar(1) NULL,
	DAYS_SUPPLY							varchar(3) NULL,
	DISPENSING_STATUS					varchar(1) NULL,
	DOB									datetime NULL,
	FILL_NUMBER							varchar(2) NULL,
	PRESCRIPTION_SERVICEREFERENCE_NO	varchar(12) NULL,
	RECORD_ID							varchar(3) NULL,
	SERVICE_PROVIDER_ID					varchar(15) NULL,
	SERVICE_PROVIDER_ID_QUALIFIER		varchar(2) NULL,
	VOID_ADJUSTED						bit NULL,
	PBP									varchar(3) NULL,
	IMPORTED_DATE						smalldatetime NULL,
	Void_Adjusted_PDE_ID				int NULL,
	PRESCRIBER_ID_QUALIFIER				varchar(2) NULL,
	PRESCRIBER_ID						varchar(15) NULL,
	MemberIDReceived				    varchar(12) NULL)