CREATE TABLE [eds].[EncounterRapsRollup](
	[EncounterRapsRollupID] [int] IDENTITY(1,1) NOT NULL,
	[EDSEncounterID] [bigint] NOT NULL,
	[PlanID] [varchar](5) NULL,
	[PlanClaimID] [varchar](50) NULL,
	[ClaimLineNumber] [varchar](50) NULL,
	[HICN] [varchar](15) NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[ProviderID] [varchar](50) NULL,
	[PlanProviderID] [varchar](50) NULL,
	[BillType] [varchar](4) NULL,
	[RevenueCode] [varchar](10) NULL,
	[ProcedureCode] [varchar](15) NULL,
	[ModifierCode] [varchar](15) NULL,
	[PlaceOfServiceCode] [varchar](15) NULL,
	[AmountBilled] [money] NULL,
	[AmountPaid] [money] NULL,
	[ProviderLastName] [varchar](100) NULL,
	[ProviderFirstName] [varchar](100) NULL,
	[PhysicianGroupName] [varchar](100) NULL,
	[AdjustedClaim] [varchar](1) NULL,
	[ReceivedDate] [datetime] NULL, 
	[ClaimTypeIndicator] [char](1) NULL, 
	[ClaimSource] [varchar] (100) NULL,
	[EncounterRapsRollupStatusID] [tinyint] NOT NULL,
	[CreatedDateTime] [datetime2](7) NOT NULL,
	[LoadID] [bigint] NOT NULL,
	[LoadDate] [datetime] NOT NULL)
