	/* AUTO-GENERATED AND COPY-PASTED FROM LINQPAD, SEE END OF FILE FOR GENERATION COMMAND */
	BEGIN TRANSACTION;
	
	TRUNCATE TABLE [dve].[TableQualifier];
	GO
	
	SET IDENTITY_INSERT [dve].[TableQualifier] ON;
	
	INSERT INTO [dve].[TableQualifier] ([ID],[TableDefinitionID],[QualifiedFieldName],[Qualifier],[Name],[Descr])
        SELECT 1, 9, NULL, 'P', 'P', NULL UNION ALL
	    SELECT 2, 9, NULL, 'T', 'T', NULL UNION ALL
	    SELECT 3, 20, NULL, 'BK', 'BK', NULL UNION ALL
	    SELECT 4, 20, NULL, 'BJ', 'BJ', NULL UNION ALL
	    SELECT 5, 20, NULL, 'BF', 'BF', NULL UNION ALL
	    SELECT 6, 20, NULL, 'PR', 'PR', NULL UNION ALL
	    SELECT 7, 20, NULL, 'BN', 'BN', NULL UNION ALL
	    SELECT 8, 24, NULL, 'FALSE', 'FALSE', NULL UNION ALL
	    SELECT 9, 24, NULL, 'TRUE', 'TRUE', NULL UNION ALL
	    SELECT 10, 28, NULL, '71', '71', NULL UNION ALL
	    SELECT 11, 28, NULL, '72', '72', NULL UNION ALL
	    SELECT 12, 28, NULL, '77', '77', NULL UNION ALL
	    SELECT 13, 28, NULL, '82', '82', NULL UNION ALL
	    SELECT 14, 28, 'ProviderTypeID', '85', 'BillingProvider', NULL UNION ALL
	    SELECT 15, 28, NULL, '87', '87', NULL UNION ALL
	    SELECT 16, 28, NULL, 'DK', 'DK', NULL UNION ALL
	    SELECT 17, 28, NULL, 'DN', 'DN', NULL UNION ALL
	    SELECT 18, 28, NULL, 'DQ', 'DQ', NULL UNION ALL
	    SELECT 19, 28, NULL, 'P3', 'P3', NULL UNION ALL
	    SELECT 20, 28, NULL, 'QB', 'QB', NULL UNION ALL
	    SELECT 21, 28, NULL, 'ZZ', 'ZZ', NULL UNION ALL
	    SELECT 22, 31, NULL, 'HC', 'HC', NULL UNION ALL
	    SELECT 23, 31, NULL, 'HP', 'HP', NULL UNION ALL
	    SELECT 24, 43, NULL, '72', '72', NULL UNION ALL
	    SELECT 25, 43, NULL, '77', '77', NULL UNION ALL
	    SELECT 26, 43, NULL, '82', '82', NULL UNION ALL
	    SELECT 27, 43, NULL, 'DK', 'DK', NULL UNION ALL
	    SELECT 28, 43, NULL, 'DN', 'DN', NULL UNION ALL
	    SELECT 29, 43, NULL, 'DQ', 'DQ', NULL UNION ALL
	    SELECT 30, 43, NULL, 'QB', 'QB', NULL UNION ALL
	    SELECT 31, 43, NULL, 'ZZ', 'ZZ', NULL UNION ALL
	    SELECT 32, 45, NULL, 'HC', 'HC', NULL UNION ALL
	    SELECT 33, 45, NULL, 'HP', 'HP', NULL UNION ALL
	    SELECT 34, 5, NULL, 'DK', 'DK', NULL UNION ALL
	    SELECT 35, 5, NULL, 'DROPOFF', 'DROPOFF', NULL UNION ALL
	    SELECT 36, 5, NULL, 'PICKUP', 'PICKUP', NULL UNION ALL
	    SELECT 37, 6, NULL, 'CONTACTS', 'CONTACTS', NULL UNION ALL
	    SELECT 38, 6, NULL, 'FRAMES', 'FRAMES', NULL UNION ALL
	    SELECT 39, 6, NULL, 'LENSES', 'LENSES', NULL UNION ALL
		SELECT 40, 20, NULL, 'ABK', 'ABK', NULL UNION ALL
	    SELECT 41, 20, NULL, 'ABJ', 'ABJ', NULL UNION ALL
	    SELECT 42, 20, NULL, 'ABF', 'ABF', NULL UNION ALL
	    SELECT 43, 20, NULL, 'APR', 'APR', NULL UNION ALL
	    SELECT 44, 20, NULL, 'ABN', 'ABN', NULL
    GO
	
	SET IDENTITY_INSERT [dve].[TableQualifier] OFF;
	
	COMMIT;
	
	
	/* TO REGENERATE THIS FILE EXECUTE THE FOLLOWING STATEMENT IN LINQPAD WITH RESULTS TO GRID */
	/* THEN COPY THE ENTIRE RESULTS GRID USING TOP LEFT CORNER AND CTRL+C AND PASTE IT OVER THIS ENTIRE FILE */
	/*     EXEC [dbo].[GeneratePostDeploymentScript] 'dve', 'TableQualifier' */
	/* EVEN THE COMMENTS WILL BE RECREATED WHEN THIS SCRIPT IS RUN */