/* AUTO-GENERATED AND COPY-PASTED FROM LINQPAD, SEE END OF FILE FOR GENERATION COMMAND */
BEGIN TRANSACTION;

TRUNCATE TABLE [edt].[FailedValidationMessage];
GO

SET IDENTITY_INSERT [edt].[FailedValidationMessage] ON;

INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 1, 'Old-School Edit Message', 'Value is Required', 'Value is Required', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 2, 'Old-School Edit Message', 'Invalid Format', 'Invalid Format', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 3, 'Old-School Edit Message', 'Invalid ID Value', 'Invalid ID Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 4, 'Old-School Edit Message', 'Must be Alpha', 'Must be Alpha', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 5, 'Old-School Edit Message', 'Must be Alphanumeric', 'Must be Alphanumeric', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 6, 'Old-School Edit Message', 'Must be a valid number with no more than 2 decimal places.', 'Must be a valid number with no more than 2 decimal places.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 7, 'Old-School Edit Message', 'Invalid UPIN', 'Invalid UPIN', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 8, 'Old-School Edit Message', 'Invalid NPI', 'Invalid NPI', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 9, 'Old-School Edit Message', 'Invalid Date Format', 'Invalid Date Format', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 10, 'Old-School Edit Message', 'Value must be between {MinLength} and {MaxLength} Characters.', 'Value must be between {MinLength} and {MaxLength} Characters.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11, 'Old-School Edit Message', 'Invalid Address', 'Invalid Address', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 12, 'Old-School Edit Message', 'Invalid HCPCS', 'Invalid HCPCS', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 13, 'Old-School Edit Message', 'Invalid Diag', 'Invalid Diag', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 14, 'Old-School Edit Message', 'Invalid Procedure Code', 'Invalid Procedure Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 15, 'Old-School Edit Message', 'Invalid Modifier', 'Invalid Modifier', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 16, 'Old-School Edit Message', 'Invalid Phone Number', 'Invalid Phone Number', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 17, 'Old-School Edit Message', 'Invalid Email', 'Invalid Email', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 18, 'Old-School Edit Message', 'Invalid Time', 'Invalid Time', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 19, 'Old-School Edit Message', 'Invalid Zip', 'Invalid Zip', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 20, 'Old-School Edit Message', 'Post Office Box not allowed', 'Post Office Box not allowed', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 21, 'Old-School Edit Message', 'Amount is less than minimum value of {MinNumericValue}.', 'Amount is less than minimum value of {MinNumericValue}.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 22, 'Old-School Edit Message', 'Amount exceeds maximum value of {MaxNumericValue}.', 'Amount exceeds maximum value of {MaxNumericValue}.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 23, 'Old-School Edit Message', 'Must Be Empty', 'Must Be Empty', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 24, 'Old-School Edit Message', 'Must be a valid number with no more than 3 decimal places.', 'Must be a valid number with no more than 3 decimal places.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 25, 'Old-School Edit Message', 'Must be a valid number with no more than 1 decimal place.', 'Must be a valid number with no more than 1 decimal place.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 26, 'Old-School Edit Message', 'Must be a valid number with no decimal places.', 'Must be a valid number with no decimal places.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 27, 'Old-School Edit Message', 'One of these fields is required ({OneOftheseRequiredWhenPopulated}).', 'One of these fields is required ({OneOftheseRequiredWhenPopulated}).', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 28, 'Old-School Edit Message', 'Only Two Accident Flags are Allowed', 'Only Two Accident Flags are Allowed', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 29, 'Old-School Edit Message', 'Diag not specific enough', 'Diag not specific enough', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 30, 'Old-School Edit Message', 'Invalid DRG Code', 'Invalid DRG Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 31, 'Old-School Edit Message', 'Must be Alphanumeric, 1st character must be Alpha', 'Must be Alphanumeric, 1st character must be Alpha', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 32, 'Old-School Edit Message', 'Must be Alphanumeric, 1st character must be Numeric', 'Must be Alphanumeric, 1st character must be Numeric', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 33, 'Old-School Edit Message', 'Invalid Value Code', 'Invalid Value Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 34, 'Old-School Edit Message', 'Invalid diagnosis qualifier for date of service. ', 'Invalid diagnosis qualifier for date of service. ', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     GO
INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 100, 'Old-School Edit Message', 'Totals Are Off', 'Totals Are Off', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 101, 'Old-School Edit Message', 'Line to claim total charge does not balance.', 'Line to claim total charge does not balance.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 102, 'Old-School Edit Message', 'Line to claim total COB payments do not balance.', 'Line to claim total COB payments do not balance.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 103, 'Old-School Edit Message', 'The sum of line paid amounts and adjustments does not equal the line charge amount.', 'The sum of line paid amounts and adjustments does not equal the line charge amount.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     GO
INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 201, 'Old-School Edit Message', 'Invalid Creatinine Results Value', 'Invalid Creatinine Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 202, 'Old-School Edit Message', 'Invalid Epoetin Results Value', 'Invalid Epoetin Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 203, 'Old-School Edit Message', 'Invalid Initial Height Results Value', 'Invalid Initial Height Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 204, 'Old-School Edit Message', 'Invalid Hematocrit Results Value', 'Invalid Hematocrit Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 205, 'Old-School Edit Message', 'Invalid Initial Hemoglobin Results Value', 'Invalid Initial Hemoglobin Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 206, 'Old-School Edit Message', 'Invalid testing Hemoglobin Results Value', 'Invalid testing Hemoglobin Results Value', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 207, 'Old-School Edit Message', 'Invalid Plan Member ID', 'Invalid Plan Member ID', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 208, 'Old-School Edit Message', 'Invalid Plan Provider ID', 'Invalid Plan Provider ID', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 209, 'Old-School Edit Message', 'Invalid Repriced Line Days', 'Invalid Repriced Line Days', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 210, 'Old-School Edit Message', 'Invalid Repriced Line Minutes', 'Invalid Repriced Line Minutes', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 211, 'Old-School Edit Message', 'Invalid SSN', 'Invalid SSN', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 212, 'Old-School Edit Message', 'Invalid HICN', 'Invalid HICN', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     GO
INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 301, 'Old-School Edit Message', 'Segment is Missing', 'Segment is Missing', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 302, 'Old-School Edit Message', 'Adjudication date must only be present at either the claim level or the service line level, not both.', 'Adjudication date must only be present at either the claim level or the service line level, not both.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 303, 'Old-School Edit Message', 'Unknown Client Plan ID.', 'Unknown Client Plan ID.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 304, 'Old-School Edit Message', 'Quanity cannot be 0 if the amount does not = 0.', 'Quanity cannot be 0 if the amount does not = 0.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 305, 'Old-School Edit Message', 'Admission Date is Required', 'Admission Date is Required', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 306, 'Old-School Edit Message', 'At least one Identifier must be in the format of an H followed by four decimals.', 'At least one Identifier must be in the format of an H followed by four decimals.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 307, 'Old-School Edit Message', 'The Primary COB must have at least one associated service line COB.', 'The Primary COB must have at least one associated service line COB.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 308, 'Old-School Edit Message', 'Duplicate Modifiers are not allowed.', 'Duplicate Modifiers are not allowed.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 309, 'Old-School Edit Message', 'Can not equal Service Start Date.', 'Can not equal Service Start Date.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 310, 'Old-School Edit Message', 'Only 2 COB records are allowed.', 'Only 2 COB records are allowed.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 311, 'Old-School Edit Message', 'Cannot have multiple Claim COB for same Payer ID.', 'Cannot have multiple Claim COB for same Payer ID.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 312, 'Old-School Edit Message', 'Cannot have multiple Line COB for same Payer ID.', 'Cannot have multiple Line COB for same Payer ID.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 313, 'Old-School Edit Message', 'All Service Lines Contain Non-Medicare Procedure Codes.', 'All Service Lines Contain Non-Medicare Procedure Codes.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 314, 'Old-School Edit Message', 'At least one, but not all Service Lines contain a Non-Medicare Procedure Code.', 'At least one, but not all Service Lines contain a Non-Medicare Procedure Code.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 315, 'Old-School Edit Message', 'Duplicate Diagnosis Code', 'Duplicate Diagnosis Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 316, 'Old-School Edit Message', 'Claim level adjudication date is invalid/missing and not all service lines are present/valid.', 'Claim level adjudication date is invalid/missing and not all service lines are present/valid.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 317, 'Old-School Edit Message', 'Primary Diagnosis cannot start with E', 'Primary Diagnosis cannot start with E', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     GO
INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 10000, 'Edit Default', 'Default message for edits.', 'Failed rule {6} for edit {5} on {7}.{8}', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 10001, 'Empty Message', 'An empty message.', '', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     GO
INSERT INTO [edt].[FailedValidationMessage] ([ID],[Name],[Descr],[Message],[Severity],[isCondition],[Edit_ID],[Edit_EntityID],[Edit_TableQualifierID],[Edit_RuleID],[Edit_ValueEntity],[Edit_ValueEntityQualifier],[Edit_Value],[Edit_RangeID],[Edit_TypeID],[Condition_ID],[Condition_Name],[Condition_Descr],[Condition_ValueEntity],[Condition_ValueEntityQualifier],[Condition_Value],[Condition_RangeID],[Condition_TypeID])         SELECT 11000, 'HIM Balancing Edit Message', 'Claim Payer Paid Amount Must Equal Sum of Service Line Payer Paid Amounts.', 'Claim Payer Paid Amount Must Equal Sum of Service Line Payer Paid Amounts.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11001, 'HIM Balancing Edit Message', 'Service Line Paid Amount must be less than or equal to Service Line Total Allowed Amount.', 'Service Line Paid Amount must be less than or equal to Service Line Total Allowed Amount.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11002, 'HIM Balancing Edit Message', 'Claim Allowed Amount must equal sum of all Service Line Allowed Amounts.', 'Claim Allowed Amount must equal sum of all Service Line Allowed Amounts.', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11003, 'Invalid revenue code', 'Invalid Revenue Code', 'Invalid Revenue Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11004, 'Invalid Patient Status Code', 'Invalid Patient Status Code', 'Invalid Patient Status Code (2 digit numeric)', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11005, 'Invalid ICD9 Procedure Code', 'Invalid ICD9 Procedure Code', 'Invalid ICD9 Procedure Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11006, 'Date cannot be before the members DOB', 'Date cannot be before the members DOB', 'Date cannot be before the members DOB', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11007, 'Invalid Occurance Code', 'Invalid Occurance Code', 'Invalid Occurance Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11008, 'Invalid Treatment Code', 'Invalid Treatment Code', 'Invalid Treatment Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL     UNION ALL
    SELECT 11009, 'Duplicated Diagnosis Code', 'Duplicate Diagnosis Code', 'Duplicate Diagnosis Code', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11010, 'Invalid ICD 10 Qualifier', 'Invalid ICD 10 Qualifier', 'Invalid ICD 10 Qualifier', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
    SELECT 11011, 'Invalid ICD 9 Qualifier', 'Invalid ICD 9 Qualifier', 'Invalid ICD 9 Qualifier', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
	SELECT 11012, 'Old-School Edit Message', 'One of these fields is required (UPIN, LicenseNumber, or PlanProviderID).', 'One of these fields is required (UPIN, LicenseNumber, or PlanProviderID).', '1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL UNION ALL
	SELECT 11013, 'Invalid Primary Diagnosis Code', 'Invalid Primary Diagnosis Code', 'Invalid Primary Diagnosis Code', 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL

    GO

	
	GO
SET IDENTITY_INSERT [edt].[FailedValidationMessage] OFF;

COMMIT;


/* TO REGENERATE THIS FILE EXECUTE THE FOLLOWING STATEMENT IN LINQPAD WITH RESULTS TO GRID */
/* THEN COPY THE ENTIRE RESULTS GRID USING TOP LEFT CORNER AND CTRL+C AND PASTE IT OVER THIS ENTIRE FILE */
/*     EXEC [dbo].[GeneratePostDeploymentScript] 'edt', 'FailedValidationMessage' */
/* EVEN THE COMMENTS WILL BE RECREATED WHEN THIS SCRIPT IS RUN */