	/* AUTO-GENERATED AND COPY-PASTED FROM LINQPAD, SEE END OF FILE FOR GENERATION COMMAND */
	BEGIN TRANSACTION;
	
	TRUNCATE TABLE [edt].[RuleCondition];
	GO
	
	SET IDENTITY_INSERT [edt].[RuleCondition] ON;
	
	
	SET IDENTITY_INSERT [edt].[RuleCondition] OFF;
	
	COMMIT;
	
	
	/* TO REGENERATE THIS FILE EXECUTE THE FOLLOWING STATEMENT IN LINQPAD WITH RESULTS TO GRID */
	/* THEN COPY THE ENTIRE RESULTS GRID USING TOP LEFT CORNER AND CTRL+C AND PASTE IT OVER THIS ENTIRE FILE */
	/*     EXEC [dbo].[GeneratePostDeploymentScript] 'edt', 'RuleCondition' */
	/* EVEN THE COMMENTS WILL BE RECREATED WHEN THIS SCRIPT IS RUN */