CREATE TABLE [edt].[Range](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Descr] [varchar](250) NULL,
	[TypeID] [tinyint] NOT NULL,
	[isActive] [bit] NOT NULL,
	[ModifiedDT] [datetime] NOT NULL,
 CONSTRAINT [PK_Range] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]